version: '3'
services:
  ethereum: 
    image: freeverseio/parity:v2.7.2-posdao-stable
    volumes:
      - ethereum-data:/home/parity/.local/share/io.parity.ethereum
  ipfs.node:
    image: freeverseio/go-ipfs:v0.5.0
    restart: always
    environment:
      - IPFS_PATH=/data
      # - IPFS_FD_MAX=4096
      - IPFS_PROFILE=server
    # volumes:
    #   - ipfs.node-data:/data
  ipfs.cluster:
    image: ipfs/ipfs-cluster:v0.12.1
    restart: always
    entrypoint: ["ipfs-cluster-follow"]
    environment: 
      - CLUSTER_IPFSHTTP_NODEMULTIADDRESS=/dns/ipfs.node/tcp/5001
    command: gr-ipfs-cluster run --init https://ipfs.io/ipns/goalrevolution.collab.ipfs.cluster.io.gorengine.com
    depends_on: 
      - ipfs.node
  universe.db:
    image: "freeverseio/universe.db:${TAG}"
    restart: always
    # volumes:
    #   - universe.db-data:/var/lib/postgresql/data
  synchronizer:
    image: "freeverseio/synchronizer:${TAG}"
    restart: always
    command: > 
      -postgres postgres://freeverse:freeverse@universe.db:5432/cryptosoccer?sslmode=disable 
      -ipfs ipfs.node:5001
      -ethereum http://ethereum:8545
      -leaguesContractAddress "${LEAGUES_CONTRACT_ADDRESS}"
      -engineContractAddress "${ENGINE_CONTRACT_ADDRESS}"
      -enginePreCompContractAddress "${ENGINEPRECOMP_CONTRACT_ADDRESS}"
      -marketContractAddress "${MARKET_CONTRACT_ADDRESS}"
      -updatesContractAddress "${UPDATES_CONTRACT_ADDRESS}"
      -assetsContractAddress "${ASSETS_CONTRACT_ADDRESS}"
      -evolutionContractAddress "${EVOLUTION_CONTRACT_ADDRESS}"
      -utilsContractAddress "${UTILS_CONTRACT_ADDRESS}"
      -playandevolveContractAddress "${PLAYANDEVOLVE_CONTRACT_ADDRESS}"
      -shopContractAddress "${SHOP_CONTRACT_CONTRACT_ADDRESS}"
      -trainingpointsContractAddress "${TRAININGPOINTS_CONTRACT_ADDRESS}"
      -constantsgettersContractAddress "${CONSTANTSGETTERS_CONTRACT_ADDRESS}"
      -delta "${BLOCKS_PER_STEP}"
    depends_on:
      - universe.db
      - ethereum
      - ipfs.node
      - ipfs.cluster
  universe.api:
    image: "freeverseio/universe.api:${TAG}"
    ports:
      - "4000:4000"
    depends_on:
      - ethereum
    command: >
      -d postgres://freeverse:freeverse@universe.db:5432/cryptosoccer 

volumes:
  ethereum-data:
  ipfs.node-data:
  universe.db-data:

