server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

scrape_configs:
- job_name: xdai
  static_configs:
  - targets:
      - localhost
    labels:
      job: xdai
      __path__: /log/xdai/*log




