package process

import (
	"database/sql"
	"encoding/hex"

	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/updates"
	"github.com/freeverseio/crypto-soccer/go/storage"
	"github.com/freeverseio/crypto-soccer/go/universe"

	log "github.com/sirupsen/logrus"
)

func (p *EventProcessor) ConsumeActionsSubmission(tx *sql.Tx, v updates.UpdatesActionsSubmission) error {
	log.Infof("[processor|consume] ActionsSubmission verse: %v, tz: %v, Day: %v, Turn: %v, cid: %v", v.Verse, v.TimeZone, v.Day, v.TurnInDay, v.IpfsCid)
	if err := p.leagueProcessor.Process(tx, v); err != nil {
		return err
	}
	u, err := universe.NewFromStorage(tx, int(v.TimeZone))
	if err != nil {
		return err
	}
	universeHash, err := u.Hash()
	if err != nil {
		return err
	}

	verse := storage.Verse{}
	verse.VerseNumber = v.Verse.Int64()
	verse.Root = hex.EncodeToString(universeHash[:])
	if err := verse.Insert(tx); err != nil {
		return err
	}

	if p.staker != nil {
		if err := p.staker.Play(*p.contracts, universeHash); err != nil {
			return err
		}
	}
	return nil
}
