package process_test

import (
	"math/big"
	"testing"

	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/assets"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/updates"
	"github.com/freeverseio/crypto-soccer/go/storage"
	"github.com/freeverseio/crypto-soccer/go/synchronizer/process"
	"github.com/freeverseio/crypto-soccer/go/useractions/postgres"
	"gotest.tools/assert"
)

func TestActionsSubmissionFirstHalfEvents(t *testing.T) {
	t.Parallel()
	tx, err := universedb.Begin()
	assert.NilError(t, err)
	defer tx.Rollback()

	timezone := uint8(1)

	divisionCreationEvent := assets.AssetsDivisionCreation{}
	divisionCreationEvent.Timezone = timezone
	divisionCreationEvent.CountryIdxInTZ = big.NewInt(0)
	divisionCreationEvent.DivisionIdxInCountry = big.NewInt(0)
	divisionCreation := process.NewDivisionCreationProcessor(bc.Contracts, namesdb)
	assert.NilError(t, divisionCreation.Process(tx, divisionCreationEvent))

	useractionsStorageService := postgres.NewUserActionsStorageService(tx)

	ua, err := useractionsStorageService.UserActionsByTimezone(int(timezone))
	assert.NilError(t, err)
	cid, err := useractionsPublishService.Publish(*ua)
	assert.NilError(t, err)
	root, err := ua.Root()
	assert.NilError(t, err)

	count, err := storage.MatchEventCount(tx)
	assert.NilError(t, err)
	assert.Equal(t, count, uint64(0))

	event := updates.UpdatesActionsSubmission{}
	event.Verse = big.NewInt(1)
	event.Seed = [32]byte{0x2}
	event.SubmissionTime = big.NewInt(1589374903)
	event.TimeZone = timezone
	event.TurnInDay = 0
	event.IpfsCid = cid
	event.Root = root
	event.Raw.BlockNumber = 10

	assert.NilError(t, process.ConsumeActionsSubmission(tx, bc.Contracts, useractionsPublishService, nil, event))
	count, err = storage.MatchEventCount(tx)
	assert.NilError(t, err)
	assert.Equal(t, count, uint64(969))
}
