package process_test

import (
	"math/big"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/assets"
	"github.com/freeverseio/crypto-soccer/go/synchronizer/process"
	"github.com/freeverseio/crypto-soccer/go/synchronizer/storage"
	"github.com/freeverseio/crypto-soccer/go/testutils"
)

func TestAssetsInitProcess(t *testing.T) {
	tx, err := universedb.Begin()
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback()
	bc, err := testutils.NewBlockchainNodeDeployAndInit()
	if err != nil {
		t.Fatal(err)
	}
	process, err := process.NewAssetsInitProcessor(bc.Contracts)
	if err != nil {
		t.Fatal(err)
	}

	creator := common.HexToAddress("123")

	event := assets.AssetsAssetsInit{
		CreatorAddr: creator,
	}
	err = process.Process(tx, event)
	if err != nil {
		t.Fatal(err)
	}
	team, err := storage.GetTeam(tx, big.NewInt(1))
	if err != nil {
		t.Fatal(err)
	}
	if team.State.Name != "Academy" {
		t.Fatalf("Wrong team name. Expected: Academy, result: %v", team)
	}
	if team.State.Owner != creator.String() {
		t.Fatalf("Wrong team owner: %v", team.State.Owner)
	}
}
