package process_test

import (
	"math/big"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/assets"
	relay "github.com/freeverseio/crypto-soccer/go/relay/storage"
	"github.com/freeverseio/crypto-soccer/go/synchronizer/process"
	"github.com/freeverseio/crypto-soccer/go/synchronizer/storage"
	"github.com/freeverseio/crypto-soccer/go/testutils"
)

func TestAssetsInitProcess(t *testing.T) {
	db, err := storage.NewSqlite3("../../../universe.db/00_schema.sql")
	if err != nil {
		t.Fatal(err)
	}
	relaydb, err := relay.NewSqlite3("../../../relay.db/00_schema.sql")
	if err != nil {
		t.Fatal(err)
	}
	bc, err := testutils.NewBlockchainNodeDeployAndInit()
	if err != nil {
		t.Fatal(err)
	}
	process, err := process.NewAssetsInitProcessor(bc.Contracts, db, relaydb)
	if err != nil {
		t.Fatal(err)
	}

	creator := common.HexToAddress("123")

	event := assets.AssetsAssetsInit{
		CreatorAddr: creator,
	}
	err = process.Process(event)
	if err != nil {
		t.Fatal(err)
	}
	team, err := db.GetTeam(big.NewInt(1))
	if err != nil {
		t.Fatal(err)
	}
	if team.Name != "Academy" {
		t.Fatalf("Wrong team name. Expected: Academy, result: %v", team)
	}
	if team.State.Owner != creator.String() {
		t.Fatalf("Wrong team owner: %v", team.State.Owner)
	}
}
