package process_test

import (
	"math/big"
	"testing"

	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/assets"
	"github.com/freeverseio/crypto-soccer/go/storage"
	"github.com/freeverseio/crypto-soccer/go/synchronizer/process"
	"gotest.tools/assert"
	"gotest.tools/golden"
)

func TestGenerateCalendarOfUnexistentLeague(t *testing.T) {
	t.Parallel()
	tx, err := universedb.Begin()
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback()
	calendar := process.NewCalendar(bc.Contracts)
	timezoneIdx := uint8(1)
	countryIdx := uint32(0)
	leagueIdx := uint32(0)
	err = calendar.Generate(tx, timezoneIdx, countryIdx, leagueIdx)
	if err == nil {
		t.Fatal("Generate calendar of unexistent league")
	}
}

func TestResetCalendar(t *testing.T) {
	t.Parallel()
	tx, err := universedb.Begin()
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback()
	calendarProcessor := process.NewCalendar(bc.Contracts)

	timezoneIdx := uint8(1)
	timezone := storage.Timezone{timezoneIdx}
	timezone.Insert(tx)
	countryIdx := uint32(0)
	country := storage.Country{timezoneIdx, countryIdx}
	country.Insert(tx)
	leagueIdx := uint32(0)
	league := storage.League{timezoneIdx, countryIdx, leagueIdx}
	league.Insert(tx)
	err = calendarProcessor.Generate(tx, timezoneIdx, countryIdx, leagueIdx)
	if err != nil {
		t.Fatal(err)
	}
	err = calendarProcessor.Reset(tx, timezoneIdx, countryIdx, leagueIdx)
	if err != nil {
		t.Fatal(err)
	}
}

func TestGenerateCalendarOfExistingLeague(t *testing.T) {
	t.Parallel()
	tx, err := universedb.Begin()
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback()
	calendarProcessor := process.NewCalendar(bc.Contracts)
	timezoneIdx := uint8(1)
	timezone := storage.Timezone{timezoneIdx}
	timezone.Insert(tx)
	countryIdx := uint32(0)
	country := storage.Country{timezoneIdx, countryIdx}
	country.Insert(tx)
	leagueIdx := uint32(0)
	league := storage.League{timezoneIdx, countryIdx, leagueIdx}
	league.Insert(tx)

	err = calendarProcessor.Generate(tx, timezoneIdx, countryIdx, leagueIdx)
	if err != nil {
		t.Fatal(err)
	}

	matches, err := storage.MatchesByTimezoneIdxCountryIdxLeagueIdx(tx, timezoneIdx, countryIdx, leagueIdx)
	assert.NilError(t, err)
	assert.Equal(t, len(matches), 56)
	golden.Assert(t, dump.Sdump(matches), t.Name()+".golden")
}

func TestCalendarPopulate(t *testing.T) {
	t.Parallel()
	tx, err := universedb.Begin()
	assert.NilError(t, err)
	defer tx.Rollback()

	divisionProcess := process.NewDivisionCreationProcessor(bc.Contracts, namesdb)

	timezone := uint8(1)
	country := uint32(0)
	event := assets.AssetsDivisionCreation{
		Timezone:             timezone,
		CountryIdxInTZ:       big.NewInt(int64(country)),
		DivisionIdxInCountry: big.NewInt(0),
	}
	assert.NilError(t, divisionProcess.Process(tx, event))

	league := uint32(0)
	day := uint8(0)
	matches, err := storage.MatchesByTimezoneIdxCountryIdxLeagueIdxMatchdayIdx(tx, timezone, country, league, day)
	assert.NilError(t, err)

	// 0 - 1
	// 7 - 2
	// 6 - 3
	// 5 - 4
	assert.Equal(t, matches[0].HomeTeamID.String(), "274877906944")
	assert.Equal(t, matches[0].VisitorTeamID.String(), "274877906945")
	assert.Equal(t, matches[1].HomeTeamID.String(), "274877906951")
	assert.Equal(t, matches[1].VisitorTeamID.String(), "274877906946")
	assert.Equal(t, matches[2].HomeTeamID.String(), "274877906950")
	assert.Equal(t, matches[2].VisitorTeamID.String(), "274877906947")
	assert.Equal(t, matches[3].HomeTeamID.String(), "274877906949")
	assert.Equal(t, matches[3].VisitorTeamID.String(), "274877906948")
}
