package process

import (
	"github.com/freeverseio/crypto-soccer/go/contracts"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/directory"
)

type DeployedDirectoryService interface {
	Consume(event directory.DirectoryDeployedDirectory) (*contracts.Contracts, error)
}

type DeployedDirectoryConsumer struct {
}

func (b DeployedDirectoryConsumer) Consume(event directory.DirectoryDeployedDirectory) (*contracts.Contracts, error) {
	return nil, nil
}
