package process

import (
	"errors"
	"math/big"

	"github.com/freeverseio/crypto-soccer/go/names"
	relay "github.com/freeverseio/crypto-soccer/go/relay/storage"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/freeverseio/crypto-soccer/go/contracts"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/assets"
	"github.com/freeverseio/crypto-soccer/go/synchronizer/storage"
	"github.com/freeverseio/crypto-soccer/go/synchronizer/utils"
	log "github.com/sirupsen/logrus"
)

type DivisionCreationProcessor struct {
	contracts             *contracts.Contracts
	universedb            *storage.Storage
	relaydb               *relay.Storage
	SK_SHO                uint8
	SK_SPE                uint8
	SK_PAS                uint8
	SK_DEF                uint8
	SK_END                uint8
	LEAGUES_PER_DIV       uint8
	TEAMS_PER_LEAGUE      uint8
	calendarProcessor     *Calendar
	PLAYERS_PER_TEAM_INIT uint8
	namesGenerator        *names.Generator
}

func NewDivisionCreationProcessor(
	contracts *contracts.Contracts,
	universedb *storage.Storage,
	relaydb *relay.Storage,
	namesdb *names.Generator,
) (*DivisionCreationProcessor, error) {
	SK_SHO, err := contracts.Assets.SKSHO(&bind.CallOpts{})
	if err != nil {
		return nil, err
	}
	SK_SPE, err := contracts.Assets.SKSPE(&bind.CallOpts{})
	if err != nil {
		return nil, err
	}
	SK_PAS, err := contracts.Assets.SKPAS(&bind.CallOpts{})
	if err != nil {
		return nil, err
	}
	SK_DEF, err := contracts.Assets.SKDEF(&bind.CallOpts{})
	if err != nil {
		return nil, err
	}
	SK_END, err := contracts.Assets.SKEND(&bind.CallOpts{})
	if err != nil {
		return nil, err
	}
	LEAGUES_PER_DIV, err := contracts.Assets.LEAGUESPERDIV(&bind.CallOpts{})
	if err != nil {
		return nil, err
	}
	TEAMS_PER_LEAGUE, err := contracts.Assets.TEAMSPERLEAGUE(&bind.CallOpts{})
	if err != nil {
		return nil, err
	}
	calendarProcessor, err := NewCalendar(contracts, universedb)
	if err != nil {
		return nil, err
	}
	PLAYERS_PER_TEAM_INIT, err := contracts.Assets.PLAYERSPERTEAMINIT(&bind.CallOpts{})
	if err != nil {
		return nil, err
	}
	return &DivisionCreationProcessor{
		contracts,
		universedb,
		relaydb,
		SK_SHO,
		SK_SPE,
		SK_PAS,
		SK_DEF,
		SK_END,
		LEAGUES_PER_DIV,
		TEAMS_PER_LEAGUE,
		calendarProcessor,
		PLAYERS_PER_TEAM_INIT,
		namesdb,
	}, nil
}

func (b *DivisionCreationProcessor) Process(event assets.AssetsDivisionCreation) error {
	log.Infof("Division Creation: timezoneIdx: %v, countryIdx %v, divisionIdx %v", event.Timezone, event.CountryIdxInTZ.Uint64(), event.DivisionIdxInCountry.Uint64())
	if event.CountryIdxInTZ.Uint64() == 0 {
		if err := b.universedb.TimezoneCreate(storage.Timezone{event.Timezone}); err != nil {
			return err
		}
	}
	if event.DivisionIdxInCountry.Uint64() == 0 {
		countryIdx := event.CountryIdxInTZ.Uint64()
		if countryIdx > 65535 {
			return errors.New("Cannot cast country idx to uint16: value too large")
		}
		if err := b.universedb.CountryCreate(storage.Country{event.Timezone, uint32(countryIdx)}); err != nil {
			return err
		}
		if err := b.storeTeamsForNewDivision(event.Timezone, event.CountryIdxInTZ, event.DivisionIdxInCountry); err != nil {
			return err
		}
	}
	return nil
}
func (b *DivisionCreationProcessor) storeTeamsForNewDivision(timezone uint8, countryIdx *big.Int, divisionIdxInCountry *big.Int) error {
	opts := &bind.CallOpts{}

	leagueIdxBegin := divisionIdxInCountry.Int64() * int64(b.LEAGUES_PER_DIV)
	leagueIdxEnd := leagueIdxBegin + int64(b.LEAGUES_PER_DIV)

	for leagueIdx := leagueIdxBegin; leagueIdx < leagueIdxEnd; leagueIdx++ {
		if err := b.universedb.LeagueCreate(storage.League{timezone, uint32(countryIdx.Uint64()), uint32(leagueIdx)}); err != nil {
			return err
		}
		teamIdxBegin := leagueIdx * int64(b.TEAMS_PER_LEAGUE)
		teamIdxEnd := teamIdxBegin + int64(b.TEAMS_PER_LEAGUE)
		for teamIdxInLeague, teamIdx := uint32(0), teamIdxBegin; teamIdx < teamIdxEnd; teamIdx, teamIdxInLeague = teamIdx+1, teamIdxInLeague+1 {
			if teamId, err := b.contracts.Assets.EncodeTZCountryAndVal(opts, timezone, countryIdx, big.NewInt(teamIdx)); err != nil {
				return err
			} else {
				teamName, errname := b.namesGenerator.GenerateTeamName(teamId, timezone, countryIdx.Uint64())
				if errname != nil {
					return errname
				}
				if err := b.universedb.TeamCreate(
					storage.Team{
						teamId,
						timezone,
						uint32(countryIdx.Uint64()),
						storage.TeamState{
							teamName,
							storage.BotOwner,
							uint32(leagueIdx),
							teamIdxInLeague,
							0,
							0,
							0,
							0,
							0,
							0,
							10,
							0,
							0,
						},
					},
				); err != nil {
					return err
				} else if err := b.storeVirtualPlayersForTeam(opts, teamId, timezone, countryIdx, teamIdx); err != nil {
					return err
				} else if err := b.createInitialTactics(teamId); err != nil {
					return err
				} else if err := b.createInitialTraining(teamId); err != nil {
					return err
				}

			}
		}

		err := b.calendarProcessor.Generate(timezone, uint32(countryIdx.Uint64()), uint32(leagueIdx))
		if err != nil {
			return err
		}
		err = b.calendarProcessor.Populate(timezone, uint32(countryIdx.Uint64()), uint32(leagueIdx))
		if err != nil {
			return err
		}
	}
	return nil
}

func (b *DivisionCreationProcessor) storeVirtualPlayersForTeam(opts *bind.CallOpts, teamId *big.Int, timezone uint8, countryIdx *big.Int, teamIdxInCountry int64) error {
	begin := teamIdxInCountry * int64(b.PLAYERS_PER_TEAM_INIT)
	end := begin + int64(b.PLAYERS_PER_TEAM_INIT)

	generation := uint8(0)
	for i := begin; i < end; i++ {
		if playerId, err := b.contracts.Assets.EncodeTZCountryAndVal(opts, timezone, countryIdx, big.NewInt(i)); err != nil {
			return err
		} else if encodedSkills, err := b.contracts.Assets.GetPlayerSkillsAtBirth(opts, playerId); err != nil {
			return err
		} else if encodedState, err := b.contracts.Assets.GetPlayerStateAtBirth(opts, playerId); err != nil {
			return err
		} else if defence, speed, pass, shoot, endurance, potential, dayOfBirth, err := utils.DecodeSkills(b.contracts.Assets, encodedSkills); err != nil {
			return err
		} else if preferredPosition, err := b.getPlayerPreferredPosition(opts, encodedSkills); err != nil {
			return err
		} else if shirtNumber, err := b.contracts.Assets.GetCurrentShirtNum(opts, encodedState); err != nil {
			return err
		} else if name, err := b.namesGenerator.GeneratePlayerFullName(playerId, generation, timezone, countryIdx.Uint64()); err != nil {
			return err
		} else if err := b.universedb.PlayerCreate(
			storage.Player{
				PlayerId:          playerId,
				PreferredPosition: preferredPosition,
				Potential:         potential.Uint64(),
				DayOfBirth:        dayOfBirth.Uint64(),
				State: storage.PlayerState{ // TODO: storage should use same skill ordering as BC
					TeamId:        teamId,
					Name:          name,
					Defence:       defence.Uint64(), // TODO: type should be uint16
					Speed:         speed.Uint64(),
					Pass:          pass.Uint64(),
					Shoot:         shoot.Uint64(),
					Endurance:     endurance.Uint64(),
					ShirtNumber:   uint8(shirtNumber.Uint64()),
					EncodedSkills: encodedSkills,
					EncodedState:  encodedState,
					Frozen:        false,
				}},
		); err != nil {
			return err
		}
	}
	return nil
}

func (p *DivisionCreationProcessor) getPlayerPreferredPosition(opts *bind.CallOpts, encodedSkills *big.Int) (string, error) {
	if forwardness, err := p.contracts.Assets.GetForwardness(opts, encodedSkills); err != nil {
		return "", err
	} else if leftishness, err := p.contracts.Assets.GetLeftishness(opts, encodedSkills); err != nil {
		return "", err
	} else {
		if forwardness.Uint64() > 255 {
			return "", errors.New("Cannot cast forwardness to uint8: value too large")
		} else if leftishness.Uint64() > 255 {
			return "", errors.New("Cannot cast leftishness to uint8: value too large")
		}
		return utils.PreferredPosition(uint8(forwardness.Uint64()), uint8(leftishness.Uint64()))
	}
}

func (b *DivisionCreationProcessor) createInitialTactics(teamID *big.Int) error {
	tactics := b.relaydb.DefaultTactic(teamID)
	initVerse := uint64(0) // init verse
	return b.relaydb.TacticCreate(*tactics, initVerse)
}

func (b *DivisionCreationProcessor) createInitialTraining(teamID *big.Int) error {
	training := relay.Training{}
	training.TeamID = teamID
	training.SpecialPlayerShirt = -1
	return b.relaydb.CreateTraining(training)
}
