package process_test

import (
	"math/big"
	"testing"

	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/assets"
	"github.com/freeverseio/crypto-soccer/go/names"
	"github.com/freeverseio/crypto-soccer/go/synchronizer/process"
	"github.com/freeverseio/crypto-soccer/go/synchronizer/storage"
	"gotest.tools/golden"
)

func TestDivisionCreationProcess(t *testing.T) {
	t.Parallel()
	tx, err := universedb.Begin()
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback()

	namesdb, err := names.New("../../names/sql/names.db")
	if err != nil {
		t.Fatal(err)
	}
	process, err := process.NewDivisionCreationProcessor(bc.Contracts, namesdb)
	if err != nil {
		t.Fatal(err)
	}

	event := assets.AssetsDivisionCreation{
		Timezone:             uint8(1),
		CountryIdxInTZ:       big.NewInt(0),
		DivisionIdxInCountry: big.NewInt(0),
	}
	err = process.Process(tx, event)
	if err != nil {
		t.Fatal(err)
	}
	player, err := storage.PlayerByPlayerId(tx, big.NewInt(274877906944))
	if err != nil {
		t.Fatal(err)
	}
	golden.Assert(t, dump.Sdump(player), t.Name()+".player.golden")
	matches, err := storage.MatchesByTimezoneIdxCountryIdxLeagueIdxMatchdayIdx(
		tx,
		1,
		0,
		0,
		0,
	)
	if err != nil {
		t.Fatal(err)
	}
	golden.Assert(t, dump.Sdump(matches), t.Name()+".matches.1.golden")
	matches, err = storage.MatchesByTimezoneIdxCountryIdxLeagueIdx(
		tx,
		1,
		0,
		0,
	)
	if err != nil {
		t.Fatal(err)
	}
	golden.Assert(t, dump.Sdump(matches), t.Name()+".matches.2.golden")
}
