package process

import (
	"database/sql"

	"github.com/freeverseio/crypto-soccer/go/contracts"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/proxy"
	log "github.com/sirupsen/logrus"
)

func ConsumeNewDirectory(tx *sql.Tx, contr contracts.Contracts, event proxy.ProxyNewDirectory) (*contracts.Contracts, error) {
	log.Infof("[processor|consume] NewDirectory event: block %v , directory %v", event.Raw.BlockNumber, event.Addr.Hex())
	var err error
	c, err := contracts.NewByNewDirectoryEvent(contr.Client, event)
	if err != nil {
		return nil, err
	}
	if err := c.ToStorage(tx); err != nil {
		return nil, err
	}
	return c, nil
}
