package process_test

import (
	"math/big"
	"testing"

	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/market"
	"github.com/freeverseio/crypto-soccer/go/synchronizer/process"
	"gotest.tools/assert"
)

func TestPlayerRetired(t *testing.T) {
	tx, err := universedb.Begin()
	assert.NilError(t, err)
	defer tx.Rollback()

	event := market.MarketPlayerRetired{}
	event.PlayerId, _ = new(big.Int).SetString("274877906957", 10)
	assert.Assert(t, event.PlayerId != nil)

	assert.Error(t, process.ConsumePlayerRetired(tx, event), "unexistent player 274877906957")
}
