package process

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"math"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/core/types"

	"github.com/freeverseio/crypto-soccer/go/contracts"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/assets"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/market"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/updates"
	"github.com/freeverseio/crypto-soccer/go/names"
	"github.com/freeverseio/crypto-soccer/go/synchronizer/storage"
	log "github.com/sirupsen/logrus"
)

type EventProcessor struct {
	contracts                 *contracts.Contracts
	assetsInitProcessor       *AssetsInitProcessor
	divisionCreationProcessor *DivisionCreationProcessor
	leagueProcessor           *LeagueProcessor
	teamTransferProcessor     *TeamTransferProcessor
}

// *****************************************************************************
// public
// *****************************************************************************

// NewEventProcessor creates a new struct for scanning and storing crypto soccer events
func NewEventProcessor(
	contracts *contracts.Contracts,
	namesdb *names.Generator,
) (*EventProcessor, error) {
	assetsInitProcessor, err := NewAssetsInitProcessor(
		contracts,
	)
	if err != nil {
		return nil, err
	}
	divisionCreationProcessor, err := NewDivisionCreationProcessor(
		contracts,
		namesdb,
	)
	if err != nil {
		return nil, err
	}
	leagueProcessor, err := NewLeagueProcessor(
		contracts,
		namesdb,
	)
	if err != nil {
		return nil, err
	}
	teamTransferProcessor, err := NewTeamTransferProcessor()
	if err != nil {
		return nil, err
	}
	return &EventProcessor{
		contracts,
		assetsInitProcessor,
		divisionCreationProcessor,
		leagueProcessor,
		teamTransferProcessor,
	}, nil
}

// Process processes all scanned events and stores them into the database db
func (p *EventProcessor) Process(tx *sql.Tx, relaytx *sql.Tx, delta uint64) (uint64, error) {

	opts, err := p.nextRange(tx, delta)
	if err != nil {
		return 0, err
	}

	if opts == nil {
		log.Info("No new blocks to scan.")
		return 0, nil
	}

	log.WithFields(log.Fields{
		"start": opts.Start,
		"end":   *opts.End,
	}).Info("Syncing ...")

	scanner := NewEventScanner(p.contracts)
	if scanner == nil {
		return opts.Start, errors.New("Unable to create scanner")
	}

	if err := scanner.Process(opts); err != nil {
		return 0, err
	}

	for _, v := range scanner.Events {
		if err := p.dispatch(tx, relaytx, v); err != nil {
			return 0, err
		}
	}

	err = storage.SetBlockNumber(tx, *opts.End)
	deltaBlock := *opts.End - opts.Start

	return deltaBlock, err
}

// *****************************************************************************
// private
// *****************************************************************************
func (p *EventProcessor) dispatch(tx *sql.Tx, relaytx *sql.Tx, e *AbstractEvent) error {
	log.Debugf("[process] dispach event block %v inBlockIndex %v", e.BlockNumber, e.TxIndexInBlock)

	switch v := e.Value.(type) {
	case assets.AssetsAssetsInit:
		log.Infof("[processor] Dispatching AssetsInit event from account %v", v.CreatorAddr)
		return p.assetsInitProcessor.Process(tx, v)
	case assets.AssetsDivisionCreation:
		log.Infof("[processor] Dispatching LeaguesDivisionCreation event Timezone %v, CountryIdxInTZ: %v, DivisionIdxInCountry %v", v.Timezone, v.CountryIdxInTZ, v.DivisionIdxInCountry)
		return p.divisionCreationProcessor.Process(tx, relaytx, v)
	case assets.AssetsTeamTransfer:
		log.Infof("[processor] dispatching LeaguesTeamTransfer event TeamID: %v, To: %v", v.TeamId, v.To)
		return p.teamTransferProcessor.Process(tx, v)
	case assets.AssetsPlayerStateChange:
		log.Infof("[processor] dispatching LeaguesPlayerStateChange event PlayerID %v", v.PlayerId)
		playerID := v.PlayerId
		state := v.State
		shirtNumber, err := p.contracts.Assets.GetCurrentShirtNum(&bind.CallOpts{}, state)
		if err != nil {
			return err
		}
		teamID, err := p.contracts.Assets.GetCurrentTeamId(&bind.CallOpts{}, state)
		if err != nil {
			return err
		}
		player, err := storage.PlayerByPlayerId(tx, playerID)
		if err != nil {
			return err
		}
		player.State.TeamId = teamID
		player.State.ShirtNumber = uint8(shirtNumber.Uint64())
		return player.Update(tx, playerID, player.State)
	case updates.UpdatesActionsSubmission:
		log.Infof("[processor] Dispatching UpdatesActionsSubmission event verse: %v, TZ: %v, Day: %v, Turn: %v, cid: %v", v.Verse, v.TimeZone, v.Day, v.TurnInDay, v.Cid)
		return p.leagueProcessor.Process(tx, v)
	case market.MarketPlayerFreeze:
		log.Infof("[processor] Dispatching MarketPlayerFreeze event PlayerID: %v Frozen: %v", v.PlayerId, v.Frozen)
		playerID := v.PlayerId
		player, err := storage.PlayerByPlayerId(tx, playerID)
		if err != nil {
			return err
		}
		player.State.Frozen = v.Frozen
		return player.Update(tx, playerID, player.State)
	}
	return fmt.Errorf("[processor] Error dispatching unknown event type: %s", e.Name)
}
func (p *EventProcessor) nextRange(tx *sql.Tx, delta uint64) (*bind.FilterOpts, error) {
	start, err := p.dbLastBlockNumber(tx)
	if err != nil {
		return nil, err
	}
	if start != 0 {
		// unless this is the very first execution,
		// the block number that is stored in the db
		// was already scanned. We are interested in
		// the next block
		if start < math.MaxUint64 {
			start += 1
		} else {
			return nil, errors.New("Block range overflow")
		}
	}
	end := p.clientLastBlockNumber()
	if delta != 0 {
		end = uint64(math.Min(float64(start+delta), float64(end)))
	}
	if start > end {
		return nil, nil
	}
	return &bind.FilterOpts{
		Start:   start,
		End:     &end,
		Context: context.Background(),
	}, nil
}

func (p *EventProcessor) clientLastBlockNumber() uint64 {
	if p.contracts.Client == nil {
		log.Warn("Client is nil. Returning 0 as last block.")
		return 0
	}
	header, err := p.contracts.Client.HeaderByNumber(context.Background(), nil)
	if err != nil {
		log.Warn("Could not get blockchain last block")
		return 0
	}
	return header.Number.Uint64()
}
func (p *EventProcessor) dbLastBlockNumber(tx *sql.Tx) (uint64, error) {
	storedLastBlockNumber, err := storage.GetBlockNumber(tx)
	if err != nil {
		return 0, err
	}
	return storedLastBlockNumber, err
}
func (p *EventProcessor) getTimeOfEvent(eventRaw types.Log) (uint64, uint64, error) {
	block, err := p.contracts.Client.BlockByHash(context.Background(), eventRaw.BlockHash)
	if err != nil {
		return 0, 0, err
	}
	return block.Time(), eventRaw.BlockNumber, nil
}
