package process

import (
	"database/sql"

	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/assets"
	"github.com/freeverseio/crypto-soccer/go/storage"
	log "github.com/sirupsen/logrus"
)

func ConsumeTeamTransfer(tx *sql.Tx, v assets.AssetsTeamTransfer) error {
	log.Infof("[processor|consume] TeamTransfer event TeamID: %v, To: %v", v.TeamId, v.To.Hex())

	teamID := v.TeamId.String()
	newOwner := v.To.String()
	team, err := storage.TeamByTeamId(tx, teamID)
	if err != nil {
		return err
	}
	// team.BlockNumber = blockNumber
	team.Owner = newOwner
	return team.Update(tx)
}
