apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/app: openethereum-failover
  app.kubernetes.io/component: openethereum-failover
resources:
  - statefulset.yaml
  - service.yaml
