apiVersion: v1
kind: Service
metadata:
  name: openethereum-failover
  labels:
    app.kubernetes.io/app: openethereum-failover
spec:
  ports:
    - port: 8545
      targetPort: 8545
  selector:
    app.kubernetes.io/app: openethereum-failover
