apiVersion: v1
kind: ConfigMap
metadata:
  name: goalrev-follower-set-bootstrap-conf
data:
  configure-ipfs.sh: |
    #!/bin/sh
    set -x
    # This is a custom entrypoint for k8s designed to run ipfs nodes in an appropriate
    # setup for production scenarios.

    if [ -f /data/ipfs/repo.lock ]; then
      rm /data/ipfs/repo.lock
    fi

    ipfs init --profile="server"
    ipfs config Datastore.StorageMax 180GB
    ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001 
    ipfs config --json Swarm.ConnMgr.HighWater 200
    ipfs config --json Datastore.BloomFilterSize 1048576

    chown -R ipfs /data/ipfs

    exit 0
