apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ipfs-cluster-follower
spec:
  serviceName: ipfs-cluster-follower
  replicas: 1
  selector:
    matchLabels:
      app: ipfs-cluster-follower
  template:
    metadata:
      labels:
        app: ipfs-cluster-follower
    spec:
      initContainers:
        - name: configure-ipfs
          image: "ipfs/go-ipfs:v0.4.23"
          command: ["sh", "/custom/configure-ipfs.sh"]
          volumeMounts:
            - name: ipfs-storage
              mountPath: /data/ipfs
            - name: configure-script
              mountPath: /custom
      containers:
        - name: ipfs
          image: "ipfs/go-ipfs:v0.4.23"
          imagePullPolicy: IfNotPresent
          env:
            - name: IPFS_FD_MAX
              value: "4096"
          ports:
            - name: swarm
              protocol: TCP
              containerPort: 4001
            - name: swarm-udp
              protocol: UDP
              containerPort: 4002
            - name: api
              protocol: TCP
              containerPort: 5001
            - name: ws
              protocol: TCP
              containerPort: 8081
            - name: http
              protocol: TCP
              containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: swarm
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
          volumeMounts:
            - mountPath: /data/ipfs
              name: ipfs-storage
            - name: configure-script
              mountPath: /custom
          resources:
            {}
        - name: ipfs-cluster
          image: "ipfs/ipfs-cluster:v0.12.1"
          command: ["/usr/local/bin/ipfs-cluster-follow", "gr-ipfs-cluster", "run", "--init", "https://ipfs.io/ipns/goalrevolution.collab.ipfs.cluster.io.gorengine.com"]
          env:
            - name: CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS
              value: "/ip4/0.0.0.0/tcp/9094"
            - name: CLUSTER_IPFSPROXY_LISTENMULTIADDRESS
              value: "/ip4/0.0.0.0/tcp/9095"
          ports:
            - name: api-http
              containerPort: 9094
              protocol: TCP
            - name: proxy-http
              containerPort: 9095
              protocol: TCP
            - name: cluster-swarm
              containerPort: 9096
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: cluster-swarm
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: cluster-storage
              mountPath: /data/ipfs-cluster
            - name: configure-script
              mountPath: /custom
          resources:
            {}

      volumes:
      - name: configure-script
        configMap:
          name: goalrev-follower-set-bootstrap-conf


  volumeClaimTemplates:
    - metadata:
        name: cluster-storage
      spec:
        storageClassName: do-block-storage 
        accessModes: ["ReadWriteOnce"]
        #persistentVolumeReclaimPolicy: Retain
        resources:
          requests:
            storage: 50Gi
    - metadata:
        name: ipfs-storage
      spec:
        storageClassName: do-block-storage 
        accessModes: ["ReadWriteOnce"]
        #persistentVolumeReclaimPolicy: Retain
        resources:
          requests:
            storage: 200Gi
