apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: cryptosoccer
  app.kubernetes.io/version: 1.0.0
resources:
- ../base
images:
- name: freeverseio/horizon
  newTag: dev
- name: freeverseio/market.db
  newTag: dev
- name: freeverseio/market.notary
  newTag: dev
- name: freeverseio/market.trader
  newTag: dev
- name: freeverseio/relay.actions
  newTag: dev
- name: freeverseio/synchronizer
  newTag: dev
- name: freeverseio/universe.api
  newTag: dev
- name: freeverseio/universe.db
  newTag: dev
replicas:
- count: 1
  name: horizon
- count: 1
  name: trader
- count: 1
  name: universeapi
patchesStrategicMerge:
- configmap.yaml
