apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- ingress.yaml
bases:
- helloworld
- universedb
- universeapi
- ipfsnode
- notary
- relayactions
- xdai
- marketdb
- horizon
- synchronizer
- trader
