apiVersion: v1
kind: Service
metadata:
  name: openethereum 
  labels:
    app.kubernetes.io/app: openethereum
spec:
  ports:
   - port: 8545
     targetPort: 8545
  selector:
   app.kubernetes.io/app: openethereum
