apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openethereum
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: openethereum # has to match .spec.template.metadata.labels
  serviceName: openethereum
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/app: openethereum # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: openethereum
        image: openethereum/openethereum:v3.2.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8545
        volumeMounts:
        - name: openethereum-storage
          mountPath: /home/openethereum/.local/share/openethereum/
        args: [--chain, xdai, 
               --no-warp,
               --base-path, /home/openethereum/.local/share/openethereum/,
               --jsonrpc-interface, all]
      initContainers:
      - name: openethereum-storage-permission-fix
        image: busybox
        command: ["/bin/chmod","-R","777", "/data"]
        volumeMounts:
        - name: openethereum-storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: openethereum-storage
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 400Gi
