version: '3'
services:
  postgres:
    build: 
      context: ./go-synchronizer/sql/.
    ports:
      - "5432:5432"
  postgraphile:
    image: graphile/postgraphile
    depends_on:
      - postgres
    command: ["postgraphile", "--connection", "postgres://freeverse:freeverse@postgres:5432/cryptosoccer", "--enhance-graphiql", "--dynamic-json"]
    ports:
      - "5000:5000"