setup:
	cd truffle-core && npm ci

contracts:
	cd truffle-core && ./node_modules/.bin/truffle compile
	cp -r truffle-core/build/contracts ./dashboard/src
	cd scripts && python2 ./deploy_go_contracts_bind_python2.py

clean:
	rm -rf ./truffle-core/build
	rm -rf ./go/contracts/autogenerated

