apiVersion: apps/v1
kind: Deployment
metadata:
  name: authproxy
  labels:
    app.kubernetes.io/app: authproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: authproxy
  template:
    metadata:
      labels:
        app.kubernetes.io/app: authproxy
    spec:
      containers:
      - name: authproxy
        image: freeverseio/authproxy:dev
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: freeverse-configmap
        args: [-timeout=30,
               -gqlurl, "http://gamelayer:4000",
               -domain, "$(domain)", "$(authproxy_extra_args)"]

      imagePullSecrets:
      - name: docker-secret
