apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: marketdb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: marketdb # has to match .spec.template.metadata.labels
  serviceName: marketdb
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/app: marketdb # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: marketdb
        image: freeverseio/market.db:dev
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: marketdb-storage
          mountPath: /var/lib/postgresql/data
      imagePullSecrets:
      - name: docker-secret
  volumeClaimTemplates:
  - metadata:
      name: marketdb-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: do-block-storage 
      resources:
        requests:
          storage: 200Gi

