apiVersion: v1
kind: Service
metadata:
  name: gameapi
  labels:
    app.kubernetes.io/app: gameapi
spec:
  selector:
    app.kubernetes.io/app: gameapi
  ports:
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 4000
