apiVersion: apps/v1
kind: Deployment
metadata:
  name: relayactions
  labels:
    app.kubernetes.io/app: relayactions
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: relayactions
  template:
    metadata:
      labels:
        app.kubernetes.io/app: relayactions
    spec:
      containers:
      - name: relayactions
        image: freeverseio/relay.actions:dev
        imagePullPolicy: Always
        env:
          - name: RELAY_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: blockchain-accounts
                key: relay
        envFrom:
          - configMapRef:
              name: freeverse-configmap
        args: [-postgres, "postgres://$(freeverse_username):$(freeverse_password)@synchronizer-with-universe-db:5432/cryptosoccer?sslmode=disable",
               -ethereum, http://xdai:8545,
               -proxy_address, "$(PROXY_CONTRACT_ADDRESS)",
               -ipfs, "/dns4/ipfsnode/tcp/5001",
               -private_key, "$(RELAY_PRIVATE_KEY)"]
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: docker-secret
