apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/app: relayactions
  app.kubernetes.io/component: relayactions
resources:
- deployment.yaml
- service.yaml
