apiVersion: v1
kind: Service
metadata:
  name: relayactions
  labels:
    app.kubernetes.io/app: relayactions
spec:
  selector:
    app.kubernetes.io/app: relayactions
  ports:
  - name: api
    port: 4000
    targetPort: 4000
