package engine

import (
	"math/big"
	"time"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/freeverseio/crypto-soccer/go/contracts"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/assets"
)

type Player struct {
	skills *big.Int
}

func NewNullPlayer() *Player {
	player := Player{}
	player.skills = big.NewInt(0)
	return &player
}

func NewPlayer(
	contracts *contracts.Contracts,
	playerID *big.Int,
	defence uint16,
	speed uint16,
	endurance uint16,
	pass uint16,
	shoot uint16,
	dayOfBirthUnix uint16,
	generation uint8,
	potential uint8,
	forwardness uint8,
	leftishness uint8,
	aggressiveness uint8,
	alignedEndOfLastHalf bool,
	redCardLastGame bool,
	gamesNonStopping uint8,
	injuryWeeksLeft uint8,
	substitutedLastHalf bool,
) (*Player, error) {
	var err error
	player := Player{}
	sumSkills := uint32(defence) + uint32(speed) + uint32(endurance) + uint32(pass) + uint32(shoot)
	player.skills, err = contracts.Engine.EncodePlayerSkills(
		&bind.CallOpts{},
		[5]uint16{shoot, speed, pass, defence, endurance},
		big.NewInt(int64(dayOfBirthUnix)),
		generation,
		playerID,
		[4]uint8{potential, forwardness, leftishness, aggressiveness},
		alignedEndOfLastHalf,
		redCardLastGame,
		gamesNonStopping,
		injuryWeeksLeft,
		substitutedLastHalf,
		sumSkills,
	)
	return &player, err
}

func NewPlayerFromSkills(skills string) *Player {
	var player Player
	player.skills, _ = new(big.Int).SetString(skills, 10)
	return &player
}

func (b Player) Skills() *big.Int {
	return new(big.Int).Set(b.skills)
}

func (b Player) Defence(assets *assets.Assets) (uint16, error) {
	opts := &bind.CallOpts{}
	value, err := assets.GetDefence(opts, b.skills)
	if err != nil {
		return 0, err
	}
	return uint16(value.Uint64()), nil
}

func (b Player) Speed(assets *assets.Assets) (uint16, error) {
	opts := &bind.CallOpts{}
	value, err := assets.GetSpeed(opts, b.skills)
	if err != nil {
		return 0, err
	}
	return uint16(value.Uint64()), nil
}

func (b Player) Pass(assets *assets.Assets) (uint16, error) {
	opts := &bind.CallOpts{}
	value, err := assets.GetPass(opts, b.skills)
	if err != nil {
		return 0, err
	}
	return uint16(value.Uint64()), nil
}
func (b Player) Shoot(assets *assets.Assets) (uint16, error) {
	opts := &bind.CallOpts{}
	value, err := assets.GetShoot(opts, b.skills)
	if err != nil {
		return 0, err
	}
	return uint16(value.Uint64()), nil
}

func (b Player) Endurance(assets *assets.Assets) (uint16, error) {
	opts := &bind.CallOpts{}
	value, err := assets.GetEndurance(opts, b.skills)
	if err != nil {
		return 0, err
	}
	return uint16(value.Uint64()), nil
}

func (b Player) Potential(assets *assets.Assets) (uint16, error) {
	opts := &bind.CallOpts{}
	value, err := assets.GetPotential(opts, b.skills)
	if err != nil {
		return 0, err
	}
	return uint16(value.Uint64()), nil
}

func (b Player) BirthDayUnix(assets *assets.Assets) (uint16, error) {
	birthDayUnix, err := assets.GetBirthDay(&bind.CallOpts{}, b.skills)
	if err != nil {
		return 0, err
	}
	return uint16(birthDayUnix.Uint64()), nil
}

func PlayerAge(birthDayUnix uint16) uint16 {
	nowInDays := time.Now().Unix() / 3600 / 24
	age := uint16((nowInDays - int64(birthDayUnix)) * 7 / 365)
	return age
}
