echo Starting geth...
geth --datadir /test/geth-testnode --mine --unlock 0x83a909262608c650bd9b0ae06e29d90d0f67ac5e --password /test/geth-testnode/passwd --keystore /test/geth-testnode/keystore --datadir test/geth-testnode/ --rpc --rpcapi personal,db,eth,net,web3,txpool,miner,debug --rpcvhosts '*' --rpccorsdomain '*' --rpcaddr '0.0.0.0' --networkid 63819 --nodiscover &
echo Waiting 2 seconds...
sleep 2
echo Installing contracts...
./node_modules/.bin/truffle migrate --network dockertest --reset
