apiVersion: v1
kind: Service
metadata:
  name: universedb
  labels:
    app: universedb
    component: database
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: universedb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: universedb
  labels:
    app: universedb
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: universedb
  template:
    metadata:
      labels:
        app: universedb
        component: database
    spec:
      containers:
      - name: universedb
        image: universedb:0.0.1
        ports:
        - containerPort: 5432
