FROM postgres:alpine

# WORKDIR /sql

# COPY ./sql/. /sql

ENV POSTGRES_USER freeverse
ENV POSTGRES_PASSWORD freeverse
ENV POSTGRES_DB cryptosoccer

# RUN PGPASSWORD=${POSTGRES_PASSWORD} psql ${POSTGRES_DB} -U ${POSTGRES_USER} -w -h localhost -p 5432

EXPOSE 5432
