package proxy2contracts

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/assets"
)

type Assets struct {
	assets.Assets
}

func NewAssets(address common.Address, backend bind.ContractBackend) (*Assets, error) {
	c, err := assets.NewAssets(address, backend)
	if err != nil {
		return nil, err
	}
	return &Assets{*c}, nil
}

func (b *Assets) GetForwardness(opts *bind.CallOpts, encodedSkills *big.Int) (*big.Int, error) {
	result := getForwardnessNat(encodedSkills)
	return result, nil
}
