apiVersion: apps/v1
kind: Deployment
metadata:
  name: trader
  labels:
    app.kubernetes.io/app: trader
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: trader
  template:
    metadata:
      labels:
        app.kubernetes.io/app: trader
    spec:
      containers:
      - name: trader
        image: freeverseio/market.trader:dev
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: freeverse-configmap
        args: [-d, "postgres://$(freeverse_username):$(freeverse_password)@marketdb:5432/market",
               -p, "4000"]
      imagePullSecrets:
      - name: docker-secret
