apiVersion: v1
kind: Service
metadata:
  name: gamelayer-webhook
  labels:
    app.kubernetes.io/app: gamelayer-webhook
spec:
  ports:
  - port: 4000
  selector:
    app.kubernetes.io/app: gamelayer-webhook
