apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd
rules:
  - apiGroups: ["", "apps", "batch", "extensions"]
    resources: ["deployments", "services", "replicasets", "pods", "jobs", "cronjobs", "ingresses", "configmaps"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd
subjects:
  - kind: ServiceAccount
    name: cicd
roleRef:
  kind: Role
  name: cicd
  apiGroup: rbac.authorization.k8s.io
