version: '3'
services:
  centauri:
    image: freeverseio/centauri:dev
    ports: 
      - "8000:8000"
    volumes:
      - centauri-data:/app/db
  postgres:
    image: freeverseio/postgres:dev
  synchronizer:
    image: freeverseio/synchronizer:dev
    command: -postgres postgres://freeverse:freeverse@postgres:5432/cryptosoccer?sslmode=disable
    depends_on:
      - postgres
  horizon:
    image: freeverseio/horizon:dev
    depends_on:
      - postgres
    command: -d postgres://freeverse:freeverse@postgres:5432/cryptosoccer
    ports:
      - "4000:4000"
  marketdb:
    image: freeverseio/marketdb:dev
  marketapi:
    image: freeverseio/marketapi:dev
    command: -d postgres://freeverse:freeverse@marketdb:5432/market -p 4001
    ports:
      - "4001:4001"
volumes:
  centauri-data:
