version: '3'
services:
  centauri:
    image: freeverseio/centauri:dev
    ports: 
      - "8000:8000"
    volumes:
      - centauri-data:/app/db
  postgres:
    image: freeverseio/postgres:dev
  synchronizer:
    image: freeverseio/synchronizer:dev
    command: -postgres postgres://freeverse:freeverse@postgres:5432/cryptosoccer?sslmode=disable
    depends_on:
      - postgres
  universeapi:
    image: freeverseio/universeapi:dev
    depends_on:
      - postgres
    command: -d postgres://freeverse:freeverse@postgres:5432/cryptosoccer
    ports:
      - "4001:4000"
  market.db:
    image: freeverseio/market.db:dev
  market.trader:
    image: freeverseio/market.trader:dev
    command: -d postgres://freeverse:freeverse@market.db:5432/market -p 4000
    ports:
      - "4002:4000"
  market.notary:
    image: freeverseio/market.notary:dev
    command: -postgres postgres://freeverse:freeverse@market.db:5432/market?sslmode=disable -assets_address "0x41dEfC329Bb70415Cf1De0f8E407168c8a73A3bA"
  relay:
    image: freeverseio/relay:dev
    ports:
      - "4003:4000"
  horizon:
    image: freeverseio/horizon:dev
    depends_on:
      - universeapi
      - market.trader
      - relay
    command: -u http://universeapi:4000/graphql -m http://market.trader:4000/graphql -r http://relay:4000/graphql
    ports:
      - "4000:4000"
volumes:
  centauri-data:
