version: '3'
services:
  ethereum: 
    image: freeverseio/ethereum:dev
    ports: 
      - "8545:8545"
    volumes:
      - ethereum-data:/test
  centauri:
    image: freeverseio/centauri:dev
    ports: 
      - "8000:8000"
    volumes:
      - centauri-data:/app/db
  postgres:
    image: freeverseio/postgres:dev
  synchronizer:
    image: freeverseio/synchronizer:dev
    command: -postgres postgres://freeverse:freeverse@postgres:5432/cryptosoccer?sslmode=disable -ethereum http://ethereum:8545
    depends_on:
      - postgres
  universeapi:
    image: freeverseio/universeapi:dev
    depends_on:
      - postgres
    command: -d postgres://freeverse:freeverse@postgres:5432/cryptosoccer
    ports:
      - "4001:4000"
  market.db:
    image: freeverseio/market.db:dev
  market.trader:
    image: freeverseio/market.trader:dev
    command: -d postgres://freeverse:freeverse@market.db:5432/market -p 4000
    ports:
      - "4002:4000"
  market.notary:
    image: freeverseio/market.notary:dev
    command: -postgres postgres://freeverse:freeverse@market.db:5432/market?sslmode=disable -market_address "0xE995621Ca05a79504EFA4193A9934Db4A92d38F5" -private_key "6cb0ca1a9699ca981d6a8efe2771e616439bf02122ce65c5ba551dbfe1347d06" -ethereum http://ethereum:8545
  relay:
    image: freeverseio/relay:dev
    ports:
      - "4003:4000"
    command: --assetsContractAddress "0x3f06d1bFE68f9A9aBfc648158F7C93faEAbd491B" --privateKey "5d0060adb17bd80efd7fff71e718bdd97acf3c6e0c633d8f7fd451044c0d1480" --ethereum "http://ethereum:8545"
  horizon:
    image: freeverseio/horizon:dev
    depends_on:
      - universeapi
      - market.trader
      - relay
    command: -u http://universeapi:4000/graphql -m http://market.trader:4000/graphql -r http://relay:4000/graphql
    ports:
      - "4000:4000"
  staker:
    image: freeverseio/staker:dev
    command: --updatesContractAddress "0xEFB926e542BB03182343aEe29ff8B36889327Acb" -i 0 --privateKey "3b650bb692288ea5d4c99c2d3e1eb77972eaeebdb04f6b2610a7d7f42de0ad27" --ethereum "http://ethereum:8545"
volumes:
  centauri-data:
  ethereum-data:
