package contracts

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/assets"
)

type AssetsProxy struct {
	assets.Assets
}

func (b *AssetsProxy) GetSpeed(opts *bind.CallOpts, encodedSkills *big.Int) (*big.Int, error) {
	result := big.NewInt(0)
	return result, nil
}
