package contracts

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/assets"
)

type AssetsNative struct {
	assets.Assets
}

func (b *AssetsNative) GetSkill(opts *bind.CallOpts, encodedSkills *big.Int, skillIdx uint8) (*big.Int, error) {
	result := new(big.Int).Set(encodedSkills)
	result.Rsh(result, uint(skillIdx)*16)
	result.And(result, big.NewInt(0xffff))
	return result, nil
}
