package contracts_test

import (
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/freeverseio/crypto-soccer/go/contracts"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/directory"
	"gotest.tools/assert"
)

func TestContractsDeploy(t *testing.T) {
	c, err := contracts.DeplyByTruffle()
	assert.NilError(t, err)
	directoryContractsAddress := c["DIRECTORY_CONTRACT_ADDRESS"]
	directoryContract, err := directory.NewDirectory(common.HexToAddress(directoryContractsAddress), client)
	assert.NilError(t, err)
	address, err := contracts.GetContractAddress(directoryContract, "ASSETS")
	assert.NilError(t, err)
	assert.Equal(t, address.String(), c["ASSETS_CONTRACT_ADDRESS"])

}
