package contracts_test

import (
	"context"
	"testing"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/freeverseio/crypto-soccer/go/contracts"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/directory"
	"gotest.tools/assert"
)

func TestContractsDeploy(t *testing.T) {
	c, err := contracts.DeplyByTruffle()
	assert.NilError(t, err)
	directoryContractsAddress := c["DIRECTORY_CONTRACT_ADDRESS"]
	directoryContract, err := directory.NewDirectory(common.HexToAddress(directoryContractsAddress), client)
	assert.NilError(t, err)
	address, err := contracts.GetContractAddress(directoryContract, "ASSETS")
	assert.NilError(t, err)
	assert.Equal(t, address.String(), c["ASSETS_CONTRACT_ADDRESS"])

}

func TestNewFromDeployedDirectory(t *testing.T) {
	c, err := contracts.DeplyByTruffle()
	assert.NilError(t, err)
	directoryContractsAddress := c["DIRECTORY_CONTRACT_ADDRESS"]
	directoryContract, err := directory.NewDirectory(common.HexToAddress(directoryContractsAddress), client)
	assert.NilError(t, err)

	iter, err := directoryContract.FilterDeployedDirectory(&bind.FilterOpts{
		Start:   0,
		End:     nil,
		Context: context.Background(),
	})
	assert.NilError(t, err)

	events := []directory.DirectoryDeployedDirectory{}
	for iter.Next() {
		events = append(events, *iter.Event)
	}
	assert.Equal(t, len(events), 1)

	contrs, err := contracts.NewFromDeployedDirectory(client, events[0])
	assert.NilError(t, err)
	t.Log(contrs)
	// TODO check the contracs are corrects
}
