# Generated by Django 2.2.3 on 2019-07-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_key',
            field=models.CharField(max_length=30),
        ),
    ]
