package match

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/assets"
)

type Player struct {
	skills *big.Int
}

func NewPlayer(skills string) *Player {
	var player Player
	player.skills, _ = new(big.Int).SetString(skills, 10)
	return &player
}

func NewNullPlayer() *Player {
	player := Player{}
	player.skills = big.NewInt(0)
	return &player
}

func (b Player) Skills() *big.Int {
	return new(big.Int).Set(b.skills)
}

func (b Player) Defence(assets *assets.Assets) (uint64, error) {
	opts := &bind.CallOpts{}
	value, err := assets.GetDefence(opts, b.skills)
	if err != nil {
		return 0, err
	}
	return value.Uint64(), nil
}

func (b Player) Speed(assets *assets.Assets) (uint64, error) {
	opts := &bind.CallOpts{}
	value, err := assets.GetSpeed(opts, b.skills)
	if err != nil {
		return 0, err
	}
	return value.Uint64(), nil
}

func (b Player) Pass(assets *assets.Assets) (uint64, error) {
	opts := &bind.CallOpts{}
	value, err := assets.GetPass(opts, b.skills)
	if err != nil {
		return 0, err
	}
	return value.Uint64(), nil
}
func (b Player) Shoot(assets *assets.Assets) (uint64, error) {
	opts := &bind.CallOpts{}
	value, err := assets.GetShoot(opts, b.skills)
	if err != nil {
		return 0, err
	}
	return value.Uint64(), nil
}

func (b Player) Endurance(assets *assets.Assets) (uint64, error) {
	opts := &bind.CallOpts{}
	value, err := assets.GetEndurance(opts, b.skills)
	if err != nil {
		return 0, err
	}
	return value.Uint64(), nil
}

func (b Player) Potential(assets *assets.Assets) (uint64, error) {
	opts := &bind.CallOpts{}
	value, err := assets.GetPotential(opts, b.skills)
	if err != nil {
		return 0, err
	}
	return value.Uint64(), nil
}

func (b Player) BirthDay(assets *assets.Assets) (uint64, error) {
	opts := &bind.CallOpts{}
	value, err := assets.GetBirthDay(opts, b.skills)
	if err != nil {
		return 0, err
	}
	return value.Uint64(), nil
}
