apiVersion: apps/v1
kind: Deployment
metadata:
  name: horizon
  labels:
    app.kubernetes.io/app: horizon
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: horizon
  template:
    metadata:
      labels:
        app.kubernetes.io/app: horizon
    spec:
      containers:
      - name: horizon
        image: freeverseio/horizon:dev
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: freeverse-configmap
        args: [-u, "http://universeapi:4000/graphql",
               -m, "http://trader:4000/graphql",
               -r, "http://relayactions:4000/graphql",
               -n, "http://notary:4000/graphql",
               "$(horizon_extra_args)"]

      imagePullSecrets:
      - name: docker-secret
