apiVersion: apps/v1
kind: Deployment
metadata:
  name: horizon
  labels:
    app: horizon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: horizon
  template:
    metadata:
      labels:
        app: horizon
    spec:
      containers:
      - name: horizon
        image: freeverseio/horizon:dev
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: freeverse-configmap
        args: [-u, "http://universeapi:4000/graphql",
               -m, "http://trader:4000/graphql"]

      imagePullSecrets:
      - name: docker-secret
