version: '3'
services:
  ethereum: 
    image: freeverseio/xdai:dev
    ports: 
      - "8545:8545"
    volumes:
      - ethereum-data:/root/.local/share/io.parity.ethereum
  web3proxy:
    image: adria0/web3proxy
    environment:
      - DEBUG=1
    ports:
      - "443:443"
    command: >
      "https://dev1.gorengine.com/pippolo" "http://ethereum:8545"
    depends_on:
      - ethereum
  universe.db:
    image: freeverseio/universe.db:$TAG
    volumes:
      - universe.db-data:/var/lib/postgresql/data
  synchronizer:
    image: freeverseio/synchronizer:$TAG
    command: > 
      -postgres postgres://freeverse:freeverse@universe.db:5432/cryptosoccer?sslmode=disable 
      -ipfs ipfs.node:5001
      -ethereum http://ethereum:8545
      -leaguesContractAddress "${LEAGUES_CONTRACT_ADDRESS}"
      -engineContractAddress "${ENGINE_CONTRACT_ADDRESS}"
      -enginePreCompContractAddress "${ENGINEPRECOMP_CONTRACT_ADDRESS}"
      -marketContractAddress "${MARKET_CONTRACT_ADDRESS}"
      -updatesContractAddress "${UPDATES_CONTRACT_ADDRESS}"
      -assetsContractAddress "${ASSETS_CONTRACT_ADDRESS}"
      -evolutionContractAddress "${EVOLUTION_CONTRACT_ADDRESS}"
      -utilsContractAddress "${UTILS_CONTRACT_ADDRESS}"
      -playandevolveContractAddress "${PLAYANDEVOLVE_CONTRACT_ADDRESS}"
      -trainingpointsContractAddress "${TRAININGPOINTS_CONTRACT_ADDRESS}"
    depends_on:
      - universe.db
      - ethereum
  universe.api:
    image: freeverseio/universe.api:$TAG
    depends_on:
      - ethereum
    command: >
      -d postgres://freeverse:freeverse@universe.db:5432/cryptosoccer 
      --assetsContractAddress "${ASSETS_CONTRACT_ADDRESS}" 
      --privateKey "5d0060adb17bd80efd7fff71e718bdd97acf3c6e0c633d8f7fd451044c0d1480" 
      --ethereum "http://ethereum:8545"
  horizon:
    image: freeverseio/horizon:$TAG
    depends_on:
      - universe.api
      - market.trader
    command: >
      -u http://universe.api:4000/graphql 
      -m http://market.trader:4000/graphql 
    ports:
      - "4000:4000"
  relay.actions:
    image: freeverseio/relay.actions:$TAG
    depends_on:
      - ethereum
      - ipfs.node
    command: >
      -postgres postgres://freeverse:freeverse@universe.db:5432/cryptosoccer?sslmode=disable 
      -private_key "3b650bb692288ea5d4c99c2d3e1eb77972eaeebdb04f6b2610a7d7f42de0ad27" 
      -ethereum "http://ethereum:8545"
      -updatesContractAddress "${UPDATES_CONTRACT_ADDRESS}" 
      -delay 30s
      -ipfs ipfs.node:5001
  ipfs.node:
    image: ipfs/go-ipfs:master
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data
    ports:
      - "4001:4001"
      # - "127.0.0.1:8080:8080"
      # - "127.0.0.1:8081:8081"
      - "127.0.0.1:5001:5001"
    volumes:
      - ipfs.node-data:/data

###############   MARKET ###################
  market.db:
    image: freeverseio/market.db:$TAG
    volumes:
      - market.db-data:/var/lib/postgresql/data
  market.trader:
    image: freeverseio/market.trader:$TAG
    command: -d postgres://freeverse:freeverse@market.db:5432/market -p 4000
  market.notary:
    image: freeverseio/market.notary:$TAG
    depends_on:
      - ethereum
    command: >
      -postgres postgres://freeverse:freeverse@market.db:5432/market?sslmode=disable  
      -private_key "3B878F7892FBBFA30C8AED1DF317C19B853685E707C2CF0EE1927DC516060A54" 
      -ethereum http://ethereum:8545 
      -market_address "${MARKET_CONTRACT_ADDRESS}" 
volumes:
  ethereum-data:
  ipfs.node-data:
  universe.db-data:
  market.db-data:


