version: '3'
services:
  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: freeverse
      POSTGRES_PASSWORD: freeverse
      POSTGRES_DB: cryptosoccer