package main

import (
	"flag"
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/ethclient"
	log "github.com/sirupsen/logrus"

	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/updates"
	"github.com/freeverseio/crypto-soccer/go/relay"
	"github.com/freeverseio/crypto-soccer/go/storage"
	"github.com/robfig/cron/v3"
)

func main() {
	postgresURL := flag.String("postgres", "postgres://freeverse:freeverse@localhost:5432/cryptosoccer?sslmode=disable", "postgres url")
	debug := flag.Bool("debug", false, "print debug logs")
	ethereumClient := flag.String("ethereum", "http://localhost:8545", "ethereum node")
	privateKeyHex := flag.String("private_key", "3B878F7892FBBFA30C8AED1DF317C19B853685E707C2CF0EE1927DC516060A54", "private key")
	updatesContractAddress := flag.String("updatesContractAddress", "", "")
	ipfsURL := flag.String("ipfs", "localhost:5001", "ipfs node url")
	flag.Parse()

	if *updatesContractAddress == "" {
		log.Fatal("no updates contract address")
	}

	if *debug {
		log.SetLevel(log.DebugLevel)
	}

	log.Info("Starting ...")

	log.Info("Dial the Ethereum client: ", *ethereumClient)
	client, err := ethclient.Dial(*ethereumClient)
	if err != nil {
		log.Fatalf("Failed to connect to the Ethereum client: %v", err)
	}

	log.Info("Creating Updates bindings to: ", *updatesContractAddress)
	updatesContract, err := updates.NewUpdates(common.HexToAddress(*updatesContractAddress), client)
	if err != nil {
		log.Fatalf("Failed to connect to the Ethereum client: %v", err)
	}

	log.Infof("ipfs URL: %v", *ipfsURL)

	log.Info("Connecting to DBMS: ", *postgresURL)
	db, err := storage.New(*postgresURL)
	if err != nil {
		log.Fatal("Failed to connect to DBMS: %v", err)
	}

	privateKey, err := crypto.HexToECDSA(*privateKeyHex)
	if err != nil {
		log.Fatal("Unable to obtain privateLey")
	}

	processor, err := relay.NewProcessor(client, privateKey, db, updatesContract, *ipfsURL)
	if err != nil {
		log.Fatal(err)
	}

	c := cron.New(cron.WithLocation(time.UTC))
	c.AddFunc("0,7,15,22,30,37,45,52 * * * *", func() {
		tx, err := db.Begin()
		if err != nil {
			log.Fatal(err)
		}
		err = processor.Process(tx)
		if err != nil {
			tx.Rollback()
			log.Fatal(err)
		}
		tx.Commit()
	})
	c.Start()

	log.Info("Running ...")
	waitForInterrupt()
	log.Info("...exiting")

	c.Stop()
}

func waitForInterrupt() {
	sigs := make(chan os.Signal, 1)
	done := make(chan bool, 1)

	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		sig := <-sigs
		fmt.Println()
		fmt.Println(sig)
		done <- true
	}()

	<-done
}
