apiVersion: v1
kind: Secret
metadata:
  name: secret-config
type: Opaque
data:
  cluster-secret: MDk5Njg3OTczNzJiYmZlOWM0YjdiYjcwYjczOGU2MWRiODE0ZmE0NGNiMzNiNGZhZWE1MjA0OTY2MDdjNjNlZA==
  peer-priv-key: Q0FFU1FGbW0xSk1BWEVFc085a3g3U0lMTTA1alV0Z3VmV1Z4Y2ZaV1hDdW93UnhDNHRjVW1NbzdHKy9STEdZb3NrWHArZVkzb2djUm5FUmxqK0R1d216dEU3az0K
