apiVersion: v1
kind: Service
metadata:
  name: ipfsnode
  labels:
    app: ipfsnode
spec:
  ports:
  - name: api
    targetPort: api
    port: 5001
  - name: proxy-http
    targetPort: proxy-http
    port: 9095
  selector:
    app: ipfs-cluster

