apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ipfs-cluster
spec:
  serviceName: ipfs-cluster
  replicas: 1
  selector:
    matchLabels:
      app: ipfs-cluster
  template:
    metadata:
      labels:
        app: ipfs-cluster
    spec:
      initContainers:
        - name: configure-ipfs
          image: "ipfs/go-ipfs:latest"
          command: ["sh", "/custom/configure-ipfs.sh"]
          volumeMounts:
            - name: ipfs-storage
              mountPath: /data/ipfs
            - name: configure-script
              mountPath: /custom
      containers:
        - name: ipfs
          image: "ipfs/go-ipfs:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: IPFS_FD_MAX
              value: "4096"
          ports:
            - name: swarm
              protocol: TCP
              containerPort: 4001
            - name: swarm-udp
              protocol: UDP
              containerPort: 4002
            - name: api
              protocol: TCP
              containerPort: 5001
            - name: ws
              protocol: TCP
              containerPort: 8081
            - name: http
              protocol: TCP
              containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: swarm
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
          volumeMounts:
            - mountPath: /data/ipfs
              name: ipfs-storage
            - name: configure-script
              mountPath: /custom
          resources:
            {}
        - name: ipfs-cluster
          image: "ipfs/ipfs-cluster:latest"
          command: ["sh", "/custom/cluster-entrypoint.sh"]
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: PEER_PRIV_KEY
              valueFrom:
                secretKeyRef:
                  key: peer-priv-key
                  name: secret-config
            - name: BOOTSTRAP_PEER_ID
              valueFrom:
                configMapKeyRef:
                  key: bootstrap-peer-id
                  name: env-config
            - name: PEER_ID
              valueFrom:
                configMapKeyRef:
                  key: peer-id
                  name: env-config
            - name: PEER_ID_1
              valueFrom:
                configMapKeyRef:
                  key: trusted-peer-id-1
                  name: env-config
            - name: PEER_ID_2
              valueFrom:
                configMapKeyRef:
                  key: trusted-peer-id-2
                  name: env-config
            - name: CLUSTER_SECRET
              valueFrom:
                secretKeyRef:
                  key: cluster-secret
                  name: secret-config
            - name: CLUSTER_CRDT_CLUSTERNAME
              value: gr-ipfs-cluster
              #- name: CLUSTER_CRDT_TRUSTEDPEERS
              #  value: "*" # change to the peer id that is allowed to change pinset i.e. "12D3KooWQykVgEXTSn3f5YHvSccvCtm37DS4MNonmCfZXpKAqiiZ"
            - name: CLUSTER_IPFSHTTP_NODEMULTIADDRESS
              value: /ip4/127.0.0.1/tcp/5001
            - name: CLUSTER_MONITOR_PING_INTERVAL
              value: 3m
            - name: GOALREV_IPFS_CLUSTER_DNS
              value: "ipfs-cluster.gorengine.com"
          ports:
            - name: api-http
              containerPort: 9094
              protocol: TCP
            - name: proxy-http
              containerPort: 9095
              protocol: TCP
            - name: cluster-swarm
              containerPort: 9096
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: cluster-swarm
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: cluster-storage
              mountPath: /data/ipfs-cluster
            - name: configure-script
              mountPath: /custom
          resources:
            {}

      volumes:
      - name: configure-script
        configMap:
          name: ipfs-cluster-set-bootstrap-conf


  volumeClaimTemplates:
    - metadata:
        name: cluster-storage
      spec:
        storageClassName: do-block-storage 
        accessModes: ["ReadWriteOnce"]
        #persistentVolumeReclaimPolicy: Retain
        resources:
          requests:
            storage: 50Gi
    - metadata:
        name: ipfs-storage
      spec:
        storageClassName: do-block-storage 
        accessModes: ["ReadWriteOnce"]
        #persistentVolumeReclaimPolicy: Retain
        resources:
          requests:
            storage: 200Gi
