apiVersion: v1
kind: Service
metadata:
  name: universeapi
  labels:
    app.kubernetes.io/app: universeapi
spec:
  selector:
    app.kubernetes.io/app: universeapi
  ports:
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 4000
