package router

import (
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/trainingpoints"
)

type Trainingpoints struct {
	trainingpoints.Trainingpoints
}

// NewTrainingpoints creates a new instance of Trainingpoints, bound to a specific deployed contract.
func NewTrainingpoints(address common.Address, backend bind.ContractBackend) (*Trainingpoints, error) {
	c, err := trainingpoints.NewTrainingpoints(address, backend)
	if err != nil {
		return nil, err
	}
	return &Trainingpoints{*c}, nil
}
