package gql

import (
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/market"
)

type Resolver struct {
	c chan interface{}
}

func NewResolver(
	c chan interface{},
	market *market.Market,
) *Resolver {
	return &Resolver{c}
}

func (b *Resolver) Ping() bool {
	return true
}
