apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamelayer
  labels:
    app.kubernetes.io/app: gamelayer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: gamelayer
  template:
    metadata:
      labels:
        app.kubernetes.io/app: gamelayer
    spec:
      containers:
      - name: gamelayer
        image: freeverseio/gamelayer:dev
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: freeverse-configmap
        env:
          - name: PG_CONNECTION_STRING
            value: postgresql://$(freeverse_username):$(freeverse_password)@gamedb:5432/game
          - name: HORIZON_URL
            value: http://horizon:4000/graphql
      imagePullSecrets:
      - name: docker-secret
