apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ipfs/go-ipfs
  newTag: v0.6.0
- name: ipfs/ipfs-cluster
  newTag: v0.13.0
replicas:
- count: 1
  name: ipfs-cluster
patchesStrategicMerge:
- env-configmap.yaml
- secret.yaml
