apiVersion: v1
kind: Secret
metadata:
  name: secret-config
type: Opaque
data:
  cluster-secret: MDk5Njg3OTczNzJiYmZlOWM0YjdiYjcwYjczOGU2MWRiODE0ZmE0NGNiMzNiNGZhZWE1MjA0OTY2MDdjNjNlZA==
  peer-priv-key: Q0FFU1FKVzZ0V0ZDZWY1WU1LVlVTb2NxajFiMjZiTGFQMW16VDdPaDZWakpEWjRST2dTNEgwOUJjbW9qVXpjUzl2M2hxS29WU0lySmk1Nm9Wb0c4QktPZng2TT0=
