apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: cryptosoccer
  app.kubernetes.io/version: 1.0.0
resources:
- ../../base
- ingress.yaml
- dashboard-ingress.yaml
- phoenix-ingress.yaml
images:
- name: freeverseio/authproxy
  newTag: 0.11.1
- name: freeverseio/dashboard
  newTag: 0.11.1
- name: freeverseio/horizon
  newTag: 0.11.1
- name: freeverseio/market.db
  newTag: 0.11.1
- name: freeverseio/market.notary
  newTag: 0.11.1
- name: freeverseio/market.trader
  newTag: 0.11.1
- name: freeverseio/relay.actions
  newTag: 0.11.1
- name: freeverseio/synchronizer
  newTag: 0.11.1
- name: freeverseio/universe.api
  newTag: 0.11.1
- name: freeverseio/universe.db
  newTag: 0.11.1
- name: freeverseio/webphoenix
  newTag: 1.1.0a1
patchesStrategicMerge:
- configmap.yaml
