apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: cryptosoccer
  app.kubernetes.io/version: 1.0.0
resources:
- ../../base
- configmap.yaml
images:
- name: freeverseio/authproxy
  newTag: 0.24.13
- name: freeverseio/dashboard
  newTag: 0.24.13
- name: freeverseio/horizon
  newTag: 0.24.13
- name: freeverseio/market.db
  newTag: 0.24.13
- name: freeverseio/market.notary
  newTag: 0.24.13
- name: freeverseio/market.trader
  newTag: 0.24.13
- name: freeverseio/relay.actions
  newTag: 0.24.13
- name: freeverseio/synchronizer
  newTag: 0.24.13
- name: freeverseio/universe.api
  newTag: 0.24.13
- name: freeverseio/universe.db
  newTag: 0.24.13
- name: freeverseio/dashboard
  newTag: 0.24.13
- name: freeverseio/gamelayer
  newTag: 0.24.13
- name: freeverseio/game.db
  newTag: 0.24.13
- name: freeverseio/gamelayer.webhook
  newTag: 0.24.13
patchesJson6902:
- target:
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
    name: cryptosoccer-ingress
  path: ingress_patch.yaml
- target:
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
    name: dashboard-external-auth-oauth2
  path: dashboard/ingress_patch.yaml
- target:
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
    name: dashboard-oauth2-proxy
  path: dashboard/ingress_patch.yaml
patches:
- target:
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
    namespace: freeverse
    name: cryptosoccer-webhook-ingress
  path: gamelayer-webhook/ingress_patch.yaml
patchesStrategicMerge:
  - synchronizer/deployment.yaml
