FROM golang:alpine

WORKDIR /app

COPY . /app
COPY ./names/sql/names.db /app

RUN apk add --no-cache alpine-sdk linux-headers
RUN cd cmd/synchronizer && go build ./synchronizer.go

ENTRYPOINT ["./cmd/synchronizer/synchronizer"]
