package relay

import (
	"crypto/ecdsa"
	"database/sql"
	"encoding/hex"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/ethclient"
	log "github.com/sirupsen/logrus"

	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/updates"
	"github.com/freeverseio/crypto-soccer/go/relay/storage"
	"github.com/freeverseio/crypto-soccer/go/useractions"
)

type Processor struct {
	updatesContract *updates.Updates
	auth            *bind.TransactOpts
	ipfsURL         string
}

// *****************************************************************************
// public
// *****************************************************************************

func NewProcessor(
	client *ethclient.Client,
	privateKey *ecdsa.PrivateKey,
	db *sql.DB,
	updatesContract *updates.Updates,
	ipfsURL string,
) (*Processor, error) {
	auth := bind.NewKeyedTransactor(privateKey)

	return &Processor{
		updatesContract,
		auth,
		ipfsURL,
	}, nil
}

func (p *Processor) Process(tx *sql.Tx) error {
	currentVerse, err := p.updatesContract.CurrentVerse(&bind.CallOpts{})
	if err != nil {
		return err
	}
	log.Infof("Staring process of verse %v", currentVerse)
	upcomingTrainings, err := storage.UpcomingTrainings(tx)
	if err != nil {
		return err
	}
	upcomingTactics, err := storage.UpcomingTactics(tx)
	if err != nil {
		return err
	}
	log.Infof("Processing %v upcoming trainings", len(upcomingTrainings))
	for i := range upcomingTrainings {
		upcomingTrainings[i].Delete(tx)
		upcomingTrainings[i].Verse = currentVerse.Uint64()
		if err = upcomingTrainings[i].Insert(tx); err != nil {
			return err
		}
	}
	log.Infof("Processing %v upcoming tactics", len(upcomingTactics))
	for i := range upcomingTactics {
		upcomingTactics[i].Delete(tx)
		upcomingTactics[i].Verse = currentVerse.Uint64()
		if err = upcomingTactics[i].Insert(tx); err != nil {
			return err
		}
	}

	actions := useractions.UserActions{}
	actions.Verse = currentVerse.Uint64()
	actions.Trainings = upcomingTrainings
	actions.Tactics = upcomingTactics
	hash, err := actions.Hash()
	if err != nil {
		return err
	}
	cid, err := actions.PushToIpfs(p.ipfsURL)
	if err != nil {
		return err
	}
	var root [32]byte
	copy(root[:], hash)

	log.Infof("[relay] submitActionsRoot root: 0x%v, cid: %v", hex.EncodeToString(root[:]), cid)
	_, err = p.updatesContract.SubmitActionsRoot(p.auth, root, cid)
	return err
}
