apiVersion: apps/v1
kind: Deployment
metadata:
  name: universedb
  labels:
    app.kubernetes.io/app: universedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: universedb
  template:
    metadata:
      labels:
        app.kubernetes.io/app: universedb
    spec:
      containers:
      - name: universedb
        image: freeverseio/universe.db:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: universedb-storage
          mountPath: "/var/lib/postgresql/data"
      imagePullSecrets:
      - name: docker-secret
      volumes:
      - name: universedb-storage
        persistentVolumeClaim:
          claimName: universedb-pvc
