apiVersion: apps/v1
kind: Deployment
metadata:
  name: universedb
  labels:
    app: universedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: universedb
  template:
    metadata:
      labels:
        app: universedb
    spec:
      containers:
      - name: universedb
        image: freeverseio/universe.db:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        #volumeMounts:
        #- mountPath: "/var/lib/postgresql/data"
        #  name: universedb-storage
      imagePullSecrets:
      - name: docker-secret
      #volumes:
      #- name: universedb-storage
      #  persistentVolumeClaim:
      #    claimName: universedb-pvclaim
