apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: universedb-pvc
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi