apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: universedb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: universedb # has to match .spec.template.metadata.labels
  serviceName: universedb
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/app: universedb # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/app
                  operator: In
                  values:
                  - synchronizer
              topologyKey: beta.kubernetes.io/os
      containers:
      - name: universedb
        image: freeverseio/universe.db:dev
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: universedb-storage
          mountPath: /var/lib/postgresql/data
      imagePullSecrets:
      - name: docker-secret
      nodeSelector:
        beta.kubernetes.io/instance-type: c-4
  volumeClaimTemplates:
  - metadata:
      name: universedb-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: do-block-storage 
      resources:
        requests:
          storage: 200Gi
