package signer

import (
	"crypto/ecdsa"
	"encoding/hex"
	"errors"
	"fmt"
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/market"
	"golang.org/x/crypto/sha3"
)

func RSV(signature string) (r [32]byte, s [32]byte, v uint8, err error) {
	if len(signature) != 132 {
		return r, s, v, errors.New("wrong signature length")
	}
	signature = signature[2:] // remove 0x
	vect, err := hex.DecodeString(signature[0:64])
	if err != nil {
		return r, s, v, err
	}
	copy(r[:], vect)
	vect, err = hex.DecodeString(signature[64:128])
	if err != nil {
		return r, s, v, err
	}
	copy(s[:], vect)
	vect, err = hex.DecodeString(signature[128:130])
	v = vect[0]
	return r, s, v, err
}

func HashPrivateMsg(currencyId uint8, price *big.Int, rnd *big.Int) (common.Hash, error) {
	uint8Ty, _ := abi.NewType("uint8", "uint8", nil)
	uint256Ty, _ := abi.NewType("uint256", "uint256", nil)
	arguments := abi.Arguments{
		{
			Type: uint8Ty,
		},
		{
			Type: uint256Ty,
		},
		{
			Type: uint256Ty,
		},
	}

	bytes, err := arguments.Pack(
		currencyId,
		price,
		rnd,
	)
	if err != nil {
		return common.Hash{}, err
	}

	return crypto.Keccak256Hash(bytes), nil
}

func HashSellMessage(
	currencyId uint8,
	price *big.Int,
	rnd *big.Int,
	validUntil int64,
	playerId *big.Int,
) (common.Hash, error) {
	var hash [32]byte
	hashPrivateMessage, err := HashPrivateMsg(
		currencyId,
		price,
		rnd,
	)
	if err != nil {
		return [32]byte{}, err
	}

	bytes32Ty, _ := abi.NewType("bytes32", "bytes32", nil)
	uint256Ty, _ := abi.NewType("uint256", "uint256", nil)
	arguments := abi.Arguments{
		{
			Type: bytes32Ty,
		},
		{
			Type: uint256Ty,
		},
		{
			Type: uint256Ty,
		},
	}

	bytes, err := arguments.Pack(
		hashPrivateMessage,
		big.NewInt(validUntil),
		playerId,
	)
	if err != nil {
		return [32]byte{}, err
	}
	copy(hash[:], crypto.Keccak256Hash(bytes).Bytes())

	ss := fmt.Sprintf("\x19Ethereum Signed Message:\n%d%s", len(hash), hash)
	return crypto.Keccak256Hash([]byte(ss)), nil
}

func HashBidMessage2(
	market *market.Market,
	auctionHashMsg [32]byte,
	extraPrice *big.Int,
	bidRnd *big.Int,
	teamID *big.Int,
	isOffer2StartAuction bool,
) (common.Hash, error) {
	var hash [32]byte
	bidHiddenPrice, err := market.HashBidHiddenPrice(
		&bind.CallOpts{},
		extraPrice,
		bidRnd,
	)
	if err != nil {
		return hash, err
	}
	hash, err = market.BuildAgreeToBuyPlayerTxMsg(
		&bind.CallOpts{},
		auctionHashMsg,
		bidHiddenPrice,
		teamID,
		isOffer2StartAuction,
	)
	if err != nil {
		return hash, err
	}
	hash, err = market.Prefixed(&bind.CallOpts{}, hash)
	return hash, err
}

func HashBidMessage(
	market *market.Market,
	currencyID uint8,
	price *big.Int,
	auctionRnd *big.Int,
	validUntil int64,
	playerID *big.Int,
	extraPrice *big.Int,
	bidRnd *big.Int,
	teamID *big.Int,
	isOffer2StartAuction bool,
) (common.Hash, error) {
	var hash [32]byte
	auctionHashMsg, err := HashSellMessage(
		currencyID,
		price,
		auctionRnd,
		validUntil,
		playerID,
	)
	if err != nil {
		return [32]byte{}, err
	}
	bidHiddenPrice, err := market.HashBidHiddenPrice(
		&bind.CallOpts{},
		extraPrice,
		bidRnd,
	)
	if err != nil {
		return hash, err
	}
	hash, err = market.BuildAgreeToBuyPlayerTxMsg(
		&bind.CallOpts{},
		auctionHashMsg,
		bidHiddenPrice,
		teamID,
		isOffer2StartAuction,
	)
	if err != nil {
		return hash, err
	}
	hash, err = market.Prefixed(&bind.CallOpts{}, hash)
	return hash, err
}

func Sign(hash []byte, pvr *ecdsa.PrivateKey) ([]byte, error) {
	sig, err := crypto.Sign(hash, pvr)
	if len(sig) != 65 {
		return []byte{}, fmt.Errorf("signature must be 65 bytes long")
	}
	if sig[64] != 0 && sig[64] != 1 {
		return []byte{}, fmt.Errorf("invalid Ethereum signature (V is not 0 or 1)")
	}
	sig[64] += 27
	return sig, err
}

func BidHiddenPrice(
	market *market.Market,
	extraPrice *big.Int,
	rnd *big.Int,
) ([32]byte, error) {
	return market.HashBidHiddenPrice(
		&bind.CallOpts{},
		extraPrice,
		rnd,
	)
}

func PublicKeyBytesToAddress(publicKey []byte) common.Address {
	var buf []byte

	hash := sha3.NewLegacyKeccak256()
	hash.Write(publicKey[1:]) // remove EC prefix 04
	buf = hash.Sum(nil)
	address := buf[12:]

	return common.HexToAddress(hex.EncodeToString(address))
}

func VerifySignature(hash []byte, signature []byte) (bool, error) {
	sigPublicKey, err := crypto.Ecrecover(hash, signature)
	if err != nil {
		return false, err
	}
	signatureNoRecoverID := signature[:len(signature)-1] // remove recovery id
	return crypto.VerifySignature(sigPublicKey, hash[:], signatureNoRecoverID), nil
}

func AddressFromSignature(hash, signature []byte) (common.Address, error) {
	sigPublicKey, err := crypto.Ecrecover(hash, signature)
	if err != nil {
		return common.Address{}, err
	}
	return PublicKeyBytesToAddress(sigPublicKey), nil
}

// func (b *Signer) HashBuyMessage(currencyId uint8, price *big.Int, rnd *big.Int, validUntil *big.Int, playerId *big.Int, teamId *big.Int) ([32]byte, error) {
// 	var hash [32]byte
// 	hashPrivateMessage, err := b.contracts.Market.HashPrivateMsg(
// 		&bind.CallOpts{},
// 		currencyId,
// 		price,
// 		rnd,
// 	)
// 	if err != nil {
// 		return hash, err
// 	}
// 	sellMsgHash, err := b.assets.BuildPutForSaleTxMsg(
// 		&bind.CallOpts{},
// 		hashPrivateMessage,
// 		validUntil,
// 		playerId,
// 	)
// 	if err != nil {
// 		return hash, err
// 	}
// 	prefixedHash, err := b.assets.Prefixed(&bind.CallOpts{}, sellMsgHash)
// 	if err != nil {
// 		return hash, err
// 	}
// 	hash, err = b.assets.BuildAgreeToBuyTxMsg(
// 		&bind.CallOpts{},
// 		prefixedHash,
// 		teamId,
// 	)
// 	if err != nil {
// 		return hash, err
// 	}
// 	hash, err = b.assets.Prefixed(&bind.CallOpts{}, hash)
// 	return hash, err
// }
