package consumer

import (
	"database/sql"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/assets"
	"github.com/freeverseio/crypto-soccer/go/contracts/autogenerated/updates"
	"github.com/freeverseio/crypto-soccer/go/relay/producer/gql"
	"github.com/freeverseio/crypto-soccer/go/relay/producer/submitactions"
	"github.com/prometheus/common/log"
)

type Consumer struct {
	ch              chan interface{}
	client          *ethclient.Client
	auth            *bind.TransactOpts
	updatesContract *updates.Updates
	assetsContract  *assets.Assets
	ipfsURL         string
	db              *sql.DB
}

func NewConsumer(
	ch chan interface{},
	client *ethclient.Client,
	auth *bind.TransactOpts,
	updatesContract *updates.Updates,
	assetsContract *assets.Assets,
	ipfsURL string,
	db *sql.DB,
) *Consumer {
	return &Consumer{
		ch,
		client,
		auth,
		updatesContract,
		assetsContract,
		ipfsURL,
		db,
	}
}

func (b *Consumer) Start() {
	firstBotTransfer := NewFirstBotTransfer(b.client, b.auth, b.assetsContract)
	actionsSubmitter := NewActionsSubmitter(b.client, b.auth, b.updatesContract, b.ipfsURL)
	for {
		event := <-b.ch
		switch ev := event.(type) {
		case gql.TransferFirstBotToAddrInput:
			log.Info("Received TransferFirstBotAddrInput")
			if err := firstBotTransfer.Process(ev); err != nil {
				log.Fatal(err)
			}
		case submitactions.SubmitActionsEvent:
			log.Info("Relay sumbit action event")
			tx, err := b.db.Begin()
			if err != nil {
				log.Fatal(err)
			}
			if err = actionsSubmitter.Process(tx); err != nil {
				tx.Rollback()
				log.Fatal(err)
			}
			if err = tx.Commit(); err != nil {
				log.Fatal(err)
			}
		default:
			log.Errorf("unknown event: %v", event)
		}
	}
}
