apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ipfs/go-ipfs
  newTag: latest
- name: ipfs/ipfs-cluster
  newTag: latest
replicas:
- count: 3
  name: ipfs-cluster
patchesStrategicMerge:
- env-configmap.yaml
- secret.yaml
