apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/app: webphoenix
  app.kubernetes.io/component: webphoenix
resources:
- deployment.yaml
- service.yaml
