
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: exampleapp
  static_configs:
  - targets:
      - localhost
    labels:
      job: exampleapp
      __path__: /log/exampleapp/*log
- job_name: xdai
  static_configs:
  - targets:
      - localhost
    labels:
      job: xdai
      __path__: /log/xdai/*log




