apiVersion: v1
kind: Service
metadata:
  name: synchronizer-with-universe-db
  labels:
    app.kubernetes.io/app: synchronizer-with-universe-db
spec:
  ports:
    - name: universedb
      port: 5432
    - name: synchronizer
      port: 4004
  selector:
    app.kubernetes.io/app: synchronizer-with-universe-db
