apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: synchronizer-with-universe-db
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: synchronizer-with-universe-db # has to match .spec.template.metadata.labels
  serviceName: synchronizer-with-universe-db
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/app: synchronizer-with-universe-db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: synchronizer
          image: freeverseio/synchronizer:dev
          imagePullPolicy: Always
          env:
            - name: STAKER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: blockchain-accounts
                  key: staker
          envFrom:
            - configMapRef:
                name: freeverse-configmap
          args:
            [
              -postgres,
              "postgres://$(freeverse_username):$(freeverse_password)@localhost:5432/cryptosoccer?sslmode=disable",
              -ethereum,
              http://openethereum:8545,
              -ipfs,
              "/dns4/ipfsnode/tcp/5001",
              -proxy_address,
              "$(PROXY_CONTRACT_ADDRESS)",
              -staker,
              "$(STAKER_PRIVATE_KEY)",
              -delta,
              "$(BLOCKS_PER_STEP)",
              -config-file,
              "$(SYNC_CONFIG_FILE)",
            ]
        - name: universedb
          image: freeverseio/universe.db:dev
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: universedb-storage
              mountPath: /var/lib/postgresql/data
      imagePullSecrets:
        - name: docker-secret
  volumeClaimTemplates:
    - metadata:
        name: universedb-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 200Gi
