apiVersion: apps/v1
kind: Deployment
metadata:
  name: notary
  labels:
    app.kubernetes.io/app: notary
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: notary
  template:
    metadata:
      labels:
        app.kubernetes.io/app: notary
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: google-iap-key
      containers:
      - name: notary
        image: freeverseio/market.notary:dev
        imagePullPolicy: Always
        env:
          - name: MARKET_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: blockchain-accounts
                key: market
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        envFrom:
          - configMapRef:
              name: freeverse-configmap
        args: [-postgres, "postgres://$(freeverse_username):$(freeverse_password)@marketdb:5432/market?sslmode=disable",
               -ethereum, http://xdai:8545,
               -private_key, "$(MARKET_PRIVATE_KEY)",
               -proxy_address, "$(PROXY_CONTRACT_ADDRESS)",
               -market_id, "$(market_id)",
               -google_key, "/var/secrets/google/key.json",
               -process_wait, "$(notary_process_wait)",
               "$(notary_extra_args)"]
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: docker-secret
