apiVersion: v1
kind: Service
metadata:
  name: notary
  labels:
    app.kubernetes.io/app: notary
spec:
  selector:
    app.kubernetes.io/app: notary
  ports:
  - name: api
    port: 4000
    targetPort: 4000
