# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['localhost:9090']

  - job_name: xdai
    scrape_interval: 10s
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        replacement: "xdai_${1}"
    static_configs:
    - targets:
      - 10.0.2.2:9368

  - job_name: ipfs
    scrape_interval: 10s
    metrics_path: /debug/metrics/prometheus
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        replacement: "ipfs_${1}"
    static_configs:
    - targets:
      - 10.0.2.4:5001

  - job_name: authproxy_1
    scrape_interval: 10s
    metrics_path: /metrics
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        replacement: "auth_1_${1}"
    static_configs:
    - targets:
      - 10.0.1.10:9090

