version: '3'
services:
  ethereum: 
    image: freeverseio/xdai:dev
    ports: 
      - "8545:8545"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - ethereum-data:/root/.local/share/io.parity.ethereum
volumes:
  ethereum-data:
