version: '3'
services:
  market-db:
    build: ./go-market/sql
  market-api:
    build: ./nodejs-market-api
    command: -d postgres://freeverse:freeverse@market-db:5432/market -p 4001
    ports:
      - "4001:4001"