apiVersion: apps/v1
kind: Deployment
metadata:
  name: synchronizer
  labels:
    app.kubernetes.io/app: synchronizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: synchronizer
  template:
    metadata:
      labels:
        app.kubernetes.io/app: synchronizer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - pool-4cpu-3b6j7
                - pool-4cpu-3b6r7
      containers:
      - name: synchronizer
        image: freeverseio/synchronizer:dev
        imagePullPolicy: Always
        env:
          - name: STAKER_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: blockchain-accounts
                key: staker
        envFrom:
          - configMapRef:
              name: freeverse-configmap
        args: [-postgres, "postgres://$(freeverse_username):$(freeverse_password)@universedb:5432/cryptosoccer?sslmode=disable",
               -ethereum, http://xdai:8545,
               -ipfs, "/dns4/ipfsnode/tcp/5001",
               -proxy_address, "$(PROXY_CONTRACT_ADDRESS)",
               -staker, "$(STAKER_PRIVATE_KEY)",
               -delta, "$(BLOCKS_PER_STEP)"]
      
      imagePullSecrets:
      - name: docker-secret
