apiVersion: apps/v1
kind: Deployment
metadata:
  name: synchronizer
  labels:
    app.kubernetes.io/app: synchronizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: synchronizer
  template:
    metadata:
      labels:
        app.kubernetes.io/app: synchronizer
    spec:
      containers:
      - name: synchronizer
        image: freeverseio/synchronizer:dev
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: freeverse-configmap
        args: [-postgres, "postgres://$(freeverse_username):$(freeverse_password)@universedb:5432/cryptosoccer?sslmode=disable",
               -ethereum, http://xdai:8545,
               -ipfs, "/dns4/ipfsnode/tcp/5001",
               -directory_address, "$(DIRECTORY_CONTRACT_ADDRESS)",
               -staker, "$(staker_private_key)",
               -delta, "$(BLOCKS_PER_STEP)"]

      imagePullSecrets:
      - name: docker-secret
