apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/app: synchronizer
  app.kubernetes.io/component: synchronizer
resources:
- deployment.yaml
- service.yaml
