apiVersion: v1
data:
  bootstrap-peer-id: QmZyN2aLhjCKrvpJ1R1gqrEevDN9fz3eHnnK1dDAuGtrGy
kind: ConfigMap
metadata:
  name: env-config
---
apiVersion: v1
data:
  cluster-entrypoint.sh: |
    #!/bin/sh
    user=ipfs

    # This is a custom entrypoint for k8s designed to connect to the bootstrap
    # node running in the cluster. It has been set up using a configmap to
    # allow changes on the fly.


    if [ ! -f /data/ipfs-cluster/service.json ]; then
      ipfs-cluster-service init
    fi

    PEER_HOSTNAME=`cat /proc/sys/kernel/hostname`

    grep -q ".*ipfs-cluster-0.*" /proc/sys/kernel/hostname
    if [ $? -eq 0 ]; then
      CLUSTER_ID=${BOOTSTRAP_PEER_ID} \
      CLUSTER_PRIVATEKEY=${BOOTSTRAP_PEER_PRIV_KEY} \
      exec ipfs-cluster-service daemon --upgrade --leave
    else
      BOOTSTRAP_ADDR=/dns4/${SVC_NAME}-0.${SVC_NAME}/tcp/9096/ipfs/${BOOTSTRAP_PEER_ID}

      if [ -z $BOOTSTRAP_ADDR ]; then
        exit 1
      fi
      # Only ipfs user can get here
      exec ipfs-cluster-service daemon --upgrade --bootstrap $BOOTSTRAP_ADDR --leave
    fi
  configure-ipfs.sh: |
    #!/bin/sh
    set -x
    # This is a custom entrypoint for k8s designed to run ipfs nodes in an appropriate
    # setup for production scenarios.

    if [ -f /data/ipfs/repo.lock ]; then
      rm /data/ipfs/repo.lock
    fi

    ipfs init --profile="server,badgerds"
    ipfs config Datastore.StorageMax 180GB
    ipfs config --json Swarm.ConnMgr.HighWater 2000
    ipfs config --json Datastore.BloomFilterSize 1048576

    chown -R ipfs /data/ipfs

    exit 0
kind: ConfigMap
metadata:
  name: ipfs-cluster-set-bootstrap-conf
---
apiVersion: v1
data:
  bootstrap-peer-priv-key: CAASrBIwggkoAgEAAoICAQDMsFI1qtuh1BN6mONbtPHZe2K/zWFKqlSD/WLzPShs3bC3nA2O7+vPq/wgc9CIOf6qMrX85RvVySrt54ptEOhOmoVTYGtYv67D87hsNHrICi1SmjqTXwSajrjRdj5sCatuRAXshr7z6ax8xfUncw3YrWFtI+7tO7V08BADxW2BSbjBIwpjC4HMSLPc93eBqAevj/YpYz8UYcR9QNdX9RhnJvttt2uky3C3My4e9TdMPDydSxJiAjloP9nfJ2m1A2v95A6/I6AYPE26jCYqnJORWjN5WRKlfw3K2oIyeKM2CHBjAR1MpBt0Irle7EOXTFuEWwhejLjpUfkuguH/aJWUAqXg8HYjllcXpd9ZplutiNidVxlsGvu+dbkVgKbn4S/5Nj2/jAXLJd+yG2MZKsoWZcwK/W5ZchA/cDCn1DwpG7NnBnL1NA7jPbSbx99578wX+lHQZCHuzMya4FHEmtkFPssNglAICB2yZl0pu5e7BrcOAzGMaPiFFAHt7tBRFDcHN4SWfrJ+0VrcSSZKLxebMgbhxiEESEyicfKSQLmE7a5OJHdCmXfWJfyLpU5kT1uxKqrYxmfqM0ELTYCgWCcWTt2eUJlVUWChhKOfIeTn8VG48XaXvmzPTZ2R2iSO3/emFjkXuNErQ+m8QrdjJ8qZqE4yEDsjlpQLUmeeUUgCWwIDAQABAoICAEOnH3TnhPJG4y1JLRRZiPol4uycGEUSaR66+CKHGz5oQ4lcRcrxl5IrOQkM3ma4LGjam/X7T6jodYzuU31a8j1QqzJ0kuZhbIUNn+37pn1Jh9NecG/XHvFqrMFmgJk61PN7/i1AGAsMN9uBnlasm237WFE3aDf23THKSrDEZz4tPKhxSXSVEBCSEwi8rj4naGrpfSYOzIGTEtuHO+Wxd6BYbQ/FaQmtyBJ1ExBeYimLW0ltz6SfMZQ4Tm2IXFLcz6u53fnk73wzKkm3GsJIwClxk8PO4e/bP5bFg/TklKU+Qs8mRiXXs889zuEF3A08yp7Da8+8WT2cv2xVDBdb3NvYdDYUQ2JHUGCd+BMJjSUekel/LhS+lalpptd0qH6ejoF6OiQsnX56QTo3LFBVJmq49Ed6M6q/8kSrCxkXonqWj8W5uqwgRB8lsrn1w2c9yHoOHmNMGdWYPv+iU1f0bNEP3Vw/kOS4eZQw4QBzgNsMASoL059qmRU5gfcp0L7Q2bn3G3AEitfBSeYv1q70H4h5EmQffWk9+uSy794geHwoZIosDivV5+fjPljA72fnu0nygwsMS1VFqK2Vgo3rhpt8aMpqXglREEb0rNZOXxFzoRWC3qwQlH3M1khidXpN62Igyg5xcnN32kkshb0LjBlUGmE1mLydtKuzS1CGHOzhAoIBAQDnVXHcHhsRgiG2dkuo1s1yVSEbQPC2Oycc5IesoinYXhTqby/Rfm6buvtXZK/f1TIRTtC2o8Jv2YI2MnB8AKvoZPqkxK+JP0GxHF3N01fwv7cG/DTOKohNkgm1Z6guu2ZAowXILCZXyV/nI6Zt5NfejWYGKVnupsU8KdW/iimAXwhhXPyjaOgAd0DMQHak6ZjiUvrdRugCiQ140wUaeQsRGKhBqrfBbbKddcg5APppCKJSKseiXYzQnZZNo8sx0mXOUL3c4ubbvD7UWFAfDW4ED4G5XPSp3LVHSGGpe/2SNpo2qH5sNyqrIgUSE97U4NzJgU3m0uUJRMB+EkksPkSLAoIBAQDig5DvDRX+2ZIZtlv2Ej1yCRelSIKeXNHVOoK/lcBx33J5vOxsfsq/9957lmogXaP8YeXyLmK6cKR2kMOAzGeSduXzybFVksLSAY+BshBrhYsrwCV6XmPiV+Pel062cd6FV8mNDQ6GEyW2G311jxIjEQOa91pc0IQ2Qnn5K445ytf6t18MT+iTGy8dlVJCfrLTL1Tz62p1fELfSAdlTtoHsKuQR0E/1R+hplSfG670FC//ts2zWMkWULyU7WuxSUXOBGMjiuVdMcsX9+HaawgzgFgBDzC1v56HlCF9rlyHj9t5f5DOv3TBywxPFYvxg+lIIUuM0CNXM4yusPmnHmNxAoIBADBs84vHhZURr6r5cncimBlB9s80te7/zP1AXaJmw+m2MByvL8xj8hWJe8ncmvB5OaTj4c8J0s8FMjvULTXYEiRw1wMc5T4OztqbfIt0nWkZSOAedZNe1e+fDYc67rrxocMQHUq86z3fOsMw9Er257V/1gaeK2RI5urkOwmAi5WCz0dKZtxyPnaygA8Bw5RcDhP6mOcvS6wUMozDZ8MV6ZonljlA2nyUURqjKEm+iazpEMmwiN/VQ3/8LRWNnyCL0aHxxvzxRrBi5Kgg4IzPi+Mvt9Esw063k/8bCM6o1PkBkyCz/tr6ZWUzluok3LWlaLKJ7dvO9AEPslfxzf2D/2cCggEBAJkiPQ9/l0ktqdn8MPuQpT286+Fvve517d3rqoz/HpVdbLTkhilrJoLVffGrZJ/w7nYncR9jQJeuo2EMyT7/8V1RSHCiAGNLzq3PJEeYLAWkyMuRIUUzHu/cX08Sl8I8BSW8jaPwGcuGkk4lE5IwYSCX1gokA1EQHvHXy0IqsgJcIdt7sKRQOXmKPTYQxwXxRdAEBbjJhLVchpEQzv8sabYdOD9YDMKswK+2FStjucmFBFYqLbJ76aZOes9sGwxF7w0yZhuXQSzaBuVzTZsuFONMdzJwJIwauYALIwEmqaN0G/ptxWYghTymmvG0LWHfvgxnhf3ykJHZZdiMCJt0reECggEAN4v21SmgHiJUl31F43uDKKOY8rT5CCaGGP4ozfA4uM2xvLRHqvGRk4RUL6j2mC+iwsAOqxk5BO2DHQH/dQEfYB3ugZ8AR8g0cPQo/VBC4hSgR4fBOjylv8uLgH17dSGRP8r1Xm5e9KjRf3mSNFHTb+sOz1SOFMYyai9M9SXCQkYaCUpUJODFNf1H2tK408g5k7y4zBJ2Oa4HWdHF2ayfP8PQ9GcqZo30wGMN4kmgqxu0i6islLHMKUF836P2H1pjSklretCaD3SskIYZaFM4akuROCSIB4C+eEP+JlxegU5xYBo4h4FBMJ9k53hrC9FZZ6lQ1g15JHuR5AieHva/lA==
  cluster-secret: NGNjYmJhOTRmYTdiMGRhNDgyOGMwZDU2MDQ0ZWY2MmViMTMwZThjM2U0MDZiY2U1ZTBiYzk2N2FjMzVhYzQyZA==
kind: Secret
metadata:
  name: secret-config
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ipfs-cluster
  name: ipfs-cluster
spec:
  ports:
  - name: swarm
    port: 4001
    targetPort: swarm
  - name: cluster-swarm
    port: 9096
    targetPort: cluster-swarm
  selector:
    app: ipfs-cluster
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ipfs-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ipfs-cluster
  serviceName: ipfs-cluster
  template:
    metadata:
      labels:
        app: ipfs-cluster
    spec:
      containers:
      - env:
        - name: IPFS_FD_MAX
          value: "4096"
        image: ipfs/go-ipfs:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 15
          tcpSocket:
            port: swarm
          timeoutSeconds: 5
        name: ipfs
        ports:
        - containerPort: 4001
          name: swarm
          protocol: TCP
        - containerPort: 4002
          name: swarm-udp
          protocol: UDP
        - containerPort: 5001
          name: api
          protocol: TCP
        - containerPort: 8081
          name: ws
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /data/ipfs
          name: ipfs-storage
        - mountPath: /custom
          name: configure-script
      - command:
        - sh
        - /custom/cluster-entrypoint.sh
        env:
        - name: BOOTSTRAP_PEER_PRIV_KEY
          value: CAASrBIwggkoAgEAAoICAQDMsFI1qtuh1BN6mONbtPHZe2K/zWFKqlSD/WLzPShs3bC3nA2O7+vPq/wgc9CIOf6qMrX85RvVySrt54ptEOhOmoVTYGtYv67D87hsNHrICi1SmjqTXwSajrjRdj5sCatuRAXshr7z6ax8xfUncw3YrWFtI+7tO7V08BADxW2BSbjBIwpjC4HMSLPc93eBqAevj/YpYz8UYcR9QNdX9RhnJvttt2uky3C3My4e9TdMPDydSxJiAjloP9nfJ2m1A2v95A6/I6AYPE26jCYqnJORWjN5WRKlfw3K2oIyeKM2CHBjAR1MpBt0Irle7EOXTFuEWwhejLjpUfkuguH/aJWUAqXg8HYjllcXpd9ZplutiNidVxlsGvu+dbkVgKbn4S/5Nj2/jAXLJd+yG2MZKsoWZcwK/W5ZchA/cDCn1DwpG7NnBnL1NA7jPbSbx99578wX+lHQZCHuzMya4FHEmtkFPssNglAICB2yZl0pu5e7BrcOAzGMaPiFFAHt7tBRFDcHN4SWfrJ+0VrcSSZKLxebMgbhxiEESEyicfKSQLmE7a5OJHdCmXfWJfyLpU5kT1uxKqrYxmfqM0ELTYCgWCcWTt2eUJlVUWChhKOfIeTn8VG48XaXvmzPTZ2R2iSO3/emFjkXuNErQ+m8QrdjJ8qZqE4yEDsjlpQLUmeeUUgCWwIDAQABAoICAEOnH3TnhPJG4y1JLRRZiPol4uycGEUSaR66+CKHGz5oQ4lcRcrxl5IrOQkM3ma4LGjam/X7T6jodYzuU31a8j1QqzJ0kuZhbIUNn+37pn1Jh9NecG/XHvFqrMFmgJk61PN7/i1AGAsMN9uBnlasm237WFE3aDf23THKSrDEZz4tPKhxSXSVEBCSEwi8rj4naGrpfSYOzIGTEtuHO+Wxd6BYbQ/FaQmtyBJ1ExBeYimLW0ltz6SfMZQ4Tm2IXFLcz6u53fnk73wzKkm3GsJIwClxk8PO4e/bP5bFg/TklKU+Qs8mRiXXs889zuEF3A08yp7Da8+8WT2cv2xVDBdb3NvYdDYUQ2JHUGCd+BMJjSUekel/LhS+lalpptd0qH6ejoF6OiQsnX56QTo3LFBVJmq49Ed6M6q/8kSrCxkXonqWj8W5uqwgRB8lsrn1w2c9yHoOHmNMGdWYPv+iU1f0bNEP3Vw/kOS4eZQw4QBzgNsMASoL059qmRU5gfcp0L7Q2bn3G3AEitfBSeYv1q70H4h5EmQffWk9+uSy794geHwoZIosDivV5+fjPljA72fnu0nygwsMS1VFqK2Vgo3rhpt8aMpqXglREEb0rNZOXxFzoRWC3qwQlH3M1khidXpN62Igyg5xcnN32kkshb0LjBlUGmE1mLydtKuzS1CGHOzhAoIBAQDnVXHcHhsRgiG2dkuo1s1yVSEbQPC2Oycc5IesoinYXhTqby/Rfm6buvtXZK/f1TIRTtC2o8Jv2YI2MnB8AKvoZPqkxK+JP0GxHF3N01fwv7cG/DTOKohNkgm1Z6guu2ZAowXILCZXyV/nI6Zt5NfejWYGKVnupsU8KdW/iimAXwhhXPyjaOgAd0DMQHak6ZjiUvrdRugCiQ140wUaeQsRGKhBqrfBbbKddcg5APppCKJSKseiXYzQnZZNo8sx0mXOUL3c4ubbvD7UWFAfDW4ED4G5XPSp3LVHSGGpe/2SNpo2qH5sNyqrIgUSE97U4NzJgU3m0uUJRMB+EkksPkSLAoIBAQDig5DvDRX+2ZIZtlv2Ej1yCRelSIKeXNHVOoK/lcBx33J5vOxsfsq/9957lmogXaP8YeXyLmK6cKR2kMOAzGeSduXzybFVksLSAY+BshBrhYsrwCV6XmPiV+Pel062cd6FV8mNDQ6GEyW2G311jxIjEQOa91pc0IQ2Qnn5K445ytf6t18MT+iTGy8dlVJCfrLTL1Tz62p1fELfSAdlTtoHsKuQR0E/1R+hplSfG670FC//ts2zWMkWULyU7WuxSUXOBGMjiuVdMcsX9+HaawgzgFgBDzC1v56HlCF9rlyHj9t5f5DOv3TBywxPFYvxg+lIIUuM0CNXM4yusPmnHmNxAoIBADBs84vHhZURr6r5cncimBlB9s80te7/zP1AXaJmw+m2MByvL8xj8hWJe8ncmvB5OaTj4c8J0s8FMjvULTXYEiRw1wMc5T4OztqbfIt0nWkZSOAedZNe1e+fDYc67rrxocMQHUq86z3fOsMw9Er257V/1gaeK2RI5urkOwmAi5WCz0dKZtxyPnaygA8Bw5RcDhP6mOcvS6wUMozDZ8MV6ZonljlA2nyUURqjKEm+iazpEMmwiN/VQ3/8LRWNnyCL0aHxxvzxRrBi5Kgg4IzPi+Mvt9Esw063k/8bCM6o1PkBkyCz/tr6ZWUzluok3LWlaLKJ7dvO9AEPslfxzf2D/2cCggEBAJkiPQ9/l0ktqdn8MPuQpT286+Fvve517d3rqoz/HpVdbLTkhilrJoLVffGrZJ/w7nYncR9jQJeuo2EMyT7/8V1RSHCiAGNLzq3PJEeYLAWkyMuRIUUzHu/cX08Sl8I8BSW8jaPwGcuGkk4lE5IwYSCX1gokA1EQHvHXy0IqsgJcIdt7sKRQOXmKPTYQxwXxRdAEBbjJhLVchpEQzv8sabYdOD9YDMKswK+2FStjucmFBFYqLbJ76aZOes9sGwxF7w0yZhuXQSzaBuVzTZsuFONMdzJwJIwauYALIwEmqaN0G/ptxWYghTymmvG0LWHfvgxnhf3ykJHZZdiMCJt0reECggEAN4v21SmgHiJUl31F43uDKKOY8rT5CCaGGP4ozfA4uM2xvLRHqvGRk4RUL6j2mC+iwsAOqxk5BO2DHQH/dQEfYB3ugZ8AR8g0cPQo/VBC4hSgR4fBOjylv8uLgH17dSGRP8r1Xm5e9KjRf3mSNFHTb+sOz1SOFMYyai9M9SXCQkYaCUpUJODFNf1H2tK408g5k7y4zBJ2Oa4HWdHF2ayfP8PQ9GcqZo30wGMN4kmgqxu0i6islLHMKUF836P2H1pjSklretCaD3SskIYZaFM4akuROCSIB4C+eEP+JlxegU5xYBo4h4FBMJ9k53hrC9FZZ6lQ1g15JHuR5AieHva/lA==
          #valueFrom:
          #  secretKeyRef:
          #    key: bootstrap-peer-priv-key
          #    name: secret-config
        - name: BOOTSTRAP_PEER_ID
          value: QmZyN2aLhjCKrvpJ1R1gqrEevDN9fz3eHnnK1dDAuGtrGy
        - name: CLUSTER_SECRET
          value: 09968797372bbfe9c4b7bb70b738e61db814fa44cb33b4faea520496607c63ed
          #valueFrom:
          #  secretKeyRef:
          #    key: cluster-secret
          #    name: secret-config
        - name: CLUSTER_MONITOR_PING_INTERVAL
          value: 3m
        - name: SVC_NAME
          value: ipfs-cluster
        envFrom:
        - configMapRef:
            name: env-config
        image: ipfs/ipfs-cluster:latest
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: cluster-swarm
          timeoutSeconds: 5
        name: ipfs-cluster
        ports:
        - containerPort: 9094
          name: api-http
          protocol: TCP
        - containerPort: 9095
          name: proxy-http
          protocol: TCP
        - containerPort: 9096
          name: cluster-swarm
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /data/ipfs-cluster
          name: cluster-storage
        - mountPath: /custom
          name: configure-script
      initContainers:
      - command:
        - sh
        - /custom/configure-ipfs.sh
        image: ipfs/go-ipfs:latest
        name: configure-ipfs
        volumeMounts:
        - mountPath: /data/ipfs
          name: ipfs-storage
        - mountPath: /custom
          name: configure-script
      volumes:
      - configMap:
          name: ipfs-cluster-set-bootstrap-conf
        name: configure-script
  volumeClaimTemplates:
  - metadata:
      name: cluster-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: do-block-storage
  - metadata:
      name: ipfs-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: do-block-storage
