apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfsnode
  labels:
    app.kubernetes.io/app: ipfsnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: ipfsnode
  template:
    metadata:
      labels:
        app.kubernetes.io/app: ipfsnode
    spec:
      containers:
      - name: ipfsnode
        image: ipfs/go-ipfs:v0.5.0-rc1
        env:
        - name: IPFS_PROFILE
          value: server
        - name: IPFS_PATH
          value: /data 
        ports:
        - name: swarm
          protocol: TCP
          containerPort: 4001
        - name: swarm-udp
          protocol: UDP
          containerPort: 4002
        - name: api
          protocol: TCP
          containerPort: 5001
        - name: ws
          protocol: TCP
          containerPort: 8081
        - name: http
          protocol: TCP
          containerPort: 8080
