apiVersion: v1
kind: Service
metadata:
  name: ipfsnode
  labels:
    app.kubernetes.io/app: ipfsnode
spec:
  ports:
  - protocol: TCP
    port: 4001
    port: 5001
  selector:
    app.kubernetes.io/app: ipfsnode
